<?php

namespace Database\Seeders;

use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\DB;

class DatabaseSeeder extends Seeder
{
    /**
     * Seed the application's database.
     */
    public function run(): void
    {
        // 1. Initialize Site Settings
        DB::table('site_settings')->updateOrInsert(
            ['key' => 'system_status'],
            ['value' => 'active', 'updated_at' => now(), 'created_at' => now()]
        );

        // 2. Create a Test Visitor User
        // REMOVED 'name' field - it is automatically generated by the database
        User::updateOrCreate(
            ['email' => 'visitor@example.com'],
            [
                'firstName'         => 'Eskedar',
                'lastName'          => 'Tesfaye',
                'password'          => Hash::make('password'),
                'role'              => 'visitor',
                'visitorType'       => 'General',
                'citizenship'       => 'Ethiopian',
                'phone_no'          => '0912345678',
                'email_verified_at' => now(),
            ]
        );

        // 3. Create an Admin User
        // REMOVED 'name' field - it is automatically generated by the database
        User::updateOrCreate(
            ['email' => 'admin@acagms.com'],
            [
                'firstName'         => 'Admin',
                'lastName'          => 'User',
                'password'          => Hash::make('admin123'),
                'role'              => 'admin',
                'visitorType'       => 'Staff',
                'citizenship'       => 'Ethiopian',
                'email_verified_at' => now(),
            ]
        );

        // 4. Call Specialized Seeders
        // Now that the users succeed, this will finally run!
        $this->call([
            HallSeeder::class,
        ]);

        $this->command->info('Database seeding completed. Admin: admin@acagms.com / admin123');
    }
}