import './bootstrap';
import '../css/app.css';

import { createApp, h, watch } from 'vue';
import { createInertiaApp } from '@inertiajs/vue3';
import { resolvePageComponent } from 'laravel-vite-plugin/inertia-helpers';
import { ZiggyVue } from '../../vendor/tightenco/ziggy'; 
import { createI18n } from 'vue-i18n';

const appName = import.meta.env.VITE_APP_NAME || 'ACAGMS';

// --- Combined & Organized Translation Messages ---
const messages = {
    en: {
        nav1: {
            dashboard: "Dashboard",
            new_booking: "New Booking",
            history: "History",
            notifications: "Notifications",
            feedback: "Feedback",
            profile: "Profile",
            settings: "Settings",
            logout: "Logout",
            main: "Main",
            preferences: "Account",
            overview: "Overview",
        },
         
        
            admin: {
    "dashboard": "Admin Panel",
    "bookings": "All Bookings",
    "halls": "Hall Assets",
    "announcements": "Broadcasts",
    "reports": "Data Reports",
    "guides": "Staff Guides",
    "feedback": "User Feedback",
    "gallery": "Gallery Admin",
    "profile": "Admin Settings",
    "security": "System Security",
    "system_health": "System Health",
    "logout": "Exit System"
  },

    register: {
        title: "Create Account",
        subtitle: "Fill in the details below to get started",
        first_name: "First Name",
        last_name: "Last Name",
        email: "Email Address",
        phone: "Phone Number",
        visitor_category: "Visitor Type",
        select_type: "Select Type",
        local: "Local Visitor",
        foreign: "Foreign Visitor",
        password: "Password",
        confirm_password: "Confirm Password",
        register_btn: "Register Now",
        have_account: "Already have an account?",
        sign_in: "Sign In",
        welcome_title: "Success!",
        welcome_text: "Your account has been created successfully.",
        validation_failed: "Registration Error",
        password_mismatch: "Passwords do not match.",
        first_name_error: "First name must contain only letters (no spaces or numbers).",
        last_name_error: "Last name must contain only letters (no spaces or numbers).",
        sidebar_title: "Welcome To Our Community",
        sidebar_desc: "Sign up today to access the official Adama City gallery, manage your visits, and stay updated with city events."
    },
  
            "admin_dashboard": {
    "dashboard": "Admin Dashboard",
    "overview": "System Overview",
    "latency": "Latency",
    "total_users": "Total Regisitred Users",
    "total_bookings": "Total Bookings",
    "pending_verification": "Pending Verification",
    "command_center": "Command Center",
    "execute_audit": "Execute Audit",
    "uptime": "Uptime",
    "load": "Load",
    "manage_users": "Manage Users",
    "view_reports": "View Reports",
    "system_settings": "System Settings",
    "live_protocols": "Live Protocols",
    "view_activity": "View Activity History"
  },
        
  
  
    "admin_Booking": {
        "registry_title": "Booking Control Center",
        "visitor": "Visitor",
        "date": "Date",
        "slot": "Slot",
        "status": "Status",
        "status_change_title": "Change Status",
        "status_confirm": "Are you sure you want to change the status for",
        "delete_title": "Are you sure?",
        "delete_warning": "You won't be able to revert this!"
    },
    "action": {
        "search_placeholder": "Search by name, ID, or date",
        "update_confirm": "Confirm Update",
        "delete": "Delete",
        "actions": "Actions"
    },
    "status": {
        "pending": "Pending",
        "approved": "Approved",
        "confirmed": "Confirmed",
        "arrived": "Arrived",
        "no_show": "No-Show",
        "cancelled": "Cancelled",
        "rejected": "Rejected",
        "completed": "Completed"
    },
  "gallery": {
        "title": "City Gallery",
        "back_home": "Back to Home",
        "header_main": "Visual",
        "header_sub": "Archive",
        "description": "A curated collection of Adama's heritage and progress.",
        "view_image": "View Image"
    },
    "admin_feedbacks": {
    "title": "Visitor Feedbacks",
    "visitor": "Visitor",
    "review_mgmt": "Review Management",
    "submissions": "submissions",
    "search_placeholder": "Search by name, email or message...",
    "all_ratings": "All Ratings",
    "stars": "Stars",
    "delete_confirm": "Are you sure you want to delete this?",
    "no_email": "No Email",
    "total_satisfied": "Total Satisfied",
    "natural_feedback": "Natural Feedback",
    "total_unsatisfied": "Total Unsatisfied",
    "no_matches": "No feedbacks found matching your criteria"
  },

        halls: {
            title: "Gallery Halls",
            subtitle: "Manage physical gallery locations and exhibition spaces",
            total: "Total Halls",
            add_new: "Add New Hall",
            edit_hall: "Edit Hall",
            name_label: "Hall Name",
            name_placeholder: "e.g. Adama History Hall",
            location_label: "Physical Location",
            location_placeholder: "e.g. Floor 1, Block B",
            desc_label: "Description",
            desc_placeholder: "Describe the purpose of this hall...",
            save: "Save Hall",
            update: "Update Hall",
            cancel: "Cancel",
            table_details: "Hall Details",
            table_location: "Location",
            table_actions: "Actions",
            delete_confirm: "Are you sure you want to delete this hall?",
            empty_title: "No halls found",
            empty_desc: "Get started by creating your first gallery hall."
        },
        
    admin_announcement: {
        "page_title": "Enterprise Alert System",
        "control_center": "Admin Control Center",
        "broadcast_title": "Emergency Broadcast",
        "broadcast_subtitle": "Notify all registered visitors immediately.",
        "target_date": "Target Date",
        "reschedule_date": "Reschedule Date",
        "optional": "(Opt)",
        "alert_title": "Alert Title",
        "alert_placeholder": "e.g., Maintenance Closure",
        "message_content": "Message Content",
        "message_placeholder": "Enter the announcement details...",
        "broadcasting": "Broadcasting...",
        "dispatch": "Dispatch Alert",
        "preview": "Live Preview",
        "preview_default_title": "Notification Title",
        "preview_default_msg": "Preview of how users will see this alert...",
        "auto_expire": "Auto-expires after date",
        "smart_tool": "Smart Tool",
        "smart_tool_desc": "Using a Reschedule Date allows the system to automatically suggest new slots to affected visitors.",
        "success": "Broadcast sent successfully!"
    },
     
  "admin_reports": {
    "title": "Admin Reports",
    "subtitle": "System Performance & Feedback Insights",
    "export_pdf": "Export PDF",
    "print": "Print",
    "registered_users": "Registered Users",
    "total_bookings": "Total Bookings",
    "total_visitors": "Total Visitors",
    "satisfied": "Satisfied",
    "unsatisfied": "Unsatisfied",
    "filter_config": "Filter Configuration",
    "time_interval": "Time Interval",
    "select_interval": "Select Time Interval",
    "weekly": "Weekly",
    "monthly": "Monthly",
    "yearly": "Yearly",
    "chart_style": "Chart Style",
    "select_chart": "Select Chart Style",
    "bar_chart": "Bar Chart",
    "line_chart": "Line Chart",
    "pie_chart": "Pie Chart",
    "apply_filters": "Apply Filters",
    "updating": "Updating...",
    "data_viz": "Data Visualization"
  },
    
    "admin_Gallery": {
        "page_title": "Gallery Management",
        "gallery": "Gallery",
        "studio": "Studio",
        "description": "Manage your digital assets and visual story.",
        "delete_selection": "Delete Selection",
        "admin_mode": "Admin Mode",
        "edit_asset": "Edit Existing Asset",
        "add_asset": "Add New Asset",
        "cancel_edit": "Cancel Edit",
        "drag_images_here": "Drag images here",
        "or": "or",
        "browse_files": "browse files",
        "from_device": "from device",
        "internal_title": "Internal Title",
        "entry_name": "Entry name...",
        "uploading": "UPLOADING...",
        "update_asset": "UPDATE ASSET",
        "publish_asset": "PUBLISH ASSET",
        "live_preview": "Live Preview",
        "awaiting_content": "Awaiting Content",
        "untitled_asset": "Untitled Asset",
        "library_catalog": "Library Catalog",
        "filter_title": "Filter by title...",
        "no_assets": "No assets found in the archive.",
        "edit": "Edit",
        "delete": "Delete",
        "enter_title": "Please enter a title",
        "asset_updated": "Asset Updated ✨",
        "image_published": "Image Published 🚀",
        "confirm_delete": "Are you sure you want to permanently remove this asset?",
        "deleted_success": "Deleted successfully",
        "delete_selected": "Delete selected items",
        "bulk_complete": "Bulk operation complete"
    },
 "admin_guides": {
    "title": "Guides Management",
    "header": "GUIDES MANAGEMENT CENTER",
    "sub_header": "System-wide Guides Management",
    "uploading": "Uploading...",
    "bulkImport": "Bulk Import",
    "total": "Total Guides",
    "assigned": "Assigned Guides",
    "unassigned": "Unassigned Guides",
    "register": "Register New Guide",
    "update": "Update Guide",
    "select": "Select...",
    "male": "Male",
    "female": "Female",
    "search": "Search by name or email...",
    "buttons": { "confirm": "Confirm Registration", "save": "Save Changes" },
    "fields": { "name": "Full Name", "email": "Email Address", "phone": "Phone Number", "gender": "Gender", "hall": "Assign Hall" }
  },
        admin_profile: {
            title: "Profile Management",
            avatar_title: "Avatar Management",
            avatar_help: "Upload a square image for best results.",
            change_photo: "Change Photo",
            first_name: "First Name",
            last_name: "Last Name",
            phone: "Phone Number",
            email: "Primary Email",
            save: "Save Changes",
            updating: "Updating..."
        },
        admin_settings: {
            title: "Security Settings",
            subtitle: "Rotate administrative access credentials",
            current_password: "Current Password",
            new_password: "New Password",
            confirm_password: "Confirm Password",
            update_btn: "Update Access Credentials",
            updating_btn: "Updating..."
        },
        system_status: {
            page_title: "System Protocol",
            header: "System Availability",
            title: "Access Control",
            subtitle: "Manage the global availability of the ACAGMS portal.",
            mode: "Mode",
            active: "Active",
            maintenance: "Maintenance",
            inactive: "Inactive",
            save_btn: "Save Protocol Changes",
            updating_btn: "Updating..."
        },
  
        // ... add the rest of your en keys here
         
        profile: {
            title: 'Account Profile',
            subtitle: 'View your registered personal information and contact details.',
            read_only: 'Read Only',
            verified_notice: 'Your profile information was verified during registration. To update these details, please visit the Adama City Administration office or contact support.',
            first_name: 'First Name',
            last_name: 'Last Name',
            email: 'Email Address',
            phone: 'Phone Number',
            security_footer: 'Your information is protected by ACAGMS security protocols.'
        },
        security: {
            title: "Account Security",
            subtitle: "Manage your credentials and protect your account.",
            page_title: "Security Settings",
            current_password: "Current Password",
            new_password: "New Password",
            confirm_password: "Confirm Password",
            placeholder_current: "Enter current password",
            placeholder_new: "Min. 8 characters",
            placeholder_confirm: "Repeat new password",
            footer_note: "Your information is protected by ACAGMS security protocols.",
            btn_update: "Update Password",
            btn_processing: "Processing...",
            success_title: "Security Updated",
            success_text: "Your password has been successfully changed."
        },
        visitor_feedback: {
      "title": "Submit Feedback",
      "header": "Provide Your Feedback",
      "lock_title": "Feedback Locked",
      "lock_text": "Please first visit halls then can send feedback.",
      "btn_dashboard": "Return to Dashboard",
      "type_general": "General Feedback",
      "type_hall": "Hall Feedback",
      "label_hall": "Select Hall",
      "placeholder_hall": "Choose a hall you visited",
      "label_subject": "Subject",
      "placeholder_subject": "What is the primary topic of your feedback?",
      "label_sentiment": "Experience Category",
      "opt_satisfaction": "Satisfaction",
      "opt_neutral": "Neutral",
      "opt_unsatisfactory": "Unsatisfactory",
      "label_rating": "Visual Rating",
      "label_message": "Detailed Feedback Message",
      "placeholder_message": "Share details about your clean or unique experiences here...",
      "btn_add_photo": "Add Photo",
      "upload_hint": "Max 3MB, JPG/PNG/WEBP",
      "btn_cancel": "Cancel",
      "btn_submit": "Submit Feedback",
      "sending": "Sending...",
      "error_title": "Error",
      "error_max_images": "You can only upload a maximum of 3 images",
      "error_format": "is not a supported format.",
      "error_size": "is too large. Max size is 3MB.",
      "error_gibberish_title": "Review Your Message",
      "error_gibberish_text": "Your message looks like gibberish. Please provide clear text descriptions.",
      "success_title": "Thank You!",
      "success_text": "Your feedback has been successfully submitted."
    },
        visitor_dashboard: {
    "nav_title": "Dashboard",
    "welcome_back": "Welcome Back",
    "hello": "Hello",
    "explore_desc": "Explore your booking options and manage your bookings!",
    "btn_book": "New Booking",
    "btn_history": "Booking History",
    "pending_bookings": "Pending Bookings",
    "approved_bookings": "Approved Bookings",
    "recent_bookings": "Recent Bookings",
    "view_all": "View All",
    "table_hall": "Hall",
    "table_date": "Date",
    "table_status": "Status",
    "table_notes": "Notes",
    "no_bookings_found": "No bookings found",
    "no_bookings_desc": "You have not scheduled any exhibition site gallery appointments yet.",
    "create_booking": "Create Booking"
  },
        visitor_booking: {
    title: 'New Booking',
    
    // Steps
    step_select_hall: 'Select Hall',
    step_visitor_type: 'Visitor Type',
    step_schedule: 'Schedule',
    
    // Headers & Subtitles
    header_choose_halls: 'Choose Booking Galleries',
    subtitle_choose_halls: 'Choose one or more galleries to continue',
    header_visitor_type: 'Select Visitor Type',
    header_schedule: 'Schedule Booking',
    
    // Categories
    category_normal: 'Normal Visitor',
    category_vip: 'VIP Visitor',
    
    // Labels
    label_date: 'Choice Date',
    label_visitor_count: 'How many Visitors?',
    label_upload_letter: 'Upload Supporting Letter',
    label_time_slot: 'Time Slot',
    
    // Slots
    slot_early_morning: 'Early Morning',
    slot_mid_morning: 'Mid Morning',
    slot_late_morning: 'Late Morning',
    slot_early_afternoon: 'Early Afternoon',
    slot_mid_afternoon: 'Mid Afternoon',
    slot_late_afternoon: 'Late Afternoon',
    
    // Buttons
    btn_continue: 'Continue',
    btn_back_halls: 'Back to Galleries',
    btn_back: 'Back',
    btn_confirm: 'Confirm Booking',
    btn_processing: 'Processing...',
    
    // Alerts & Alerts texts
    alert_restricted_title: 'Booking Restricted',
    alert_select_hall_title: 'Select Hall',
    alert_select_hall_text: 'Please select at least one gallery/hall',
    alert_weekend_title: 'Weekend Not Allowed',
    alert_weekend_text: 'Only Monday–Friday bookings allowed',
    alert_missing_doc_title: 'Missing Document',
    alert_missing_doc_text: 'VIP bookings require official letter',
    alert_select_slot_title: 'Select Time Slot',
    alert_select_slot_text: 'Please pick a time slot before confirming',
    alert_success_text: 'Booking successfully saved!',
    alert_failed_title: 'Request Failed',
    alert_failed_text: 'Please check your input details'
},
        login: {
            title: "Log in",
            subtitle: "Digital Government Services",
            welcome: "Welcome Back",
            description: "If you have an account, please sign in to continue to the dashboard",
            email_label: "Email Address",
            email_placeholder: "Enter your email",
            brand_city: "ADAMA CITY",
            brand_admin: "ADMINISTRATION",
            sidebar_subtitle: "GALLERY MANAGEMENT SYSTEM",
            password_label: "Password",
            forgot_password: "Forgot password?",
            remember_me: "Remember me",
            sign_in_btn: "Sign In to Dashboard",
            authenticating: "Authenticating...",
            no_account: "Don't have an account?",
            sign_up: "Sign up",
            footer: "© 2026 Adama City Administration - Smart City Initiative"
        },
        history: {
            qr_pass: 'QR Pass',
            actions: 'Actions',
            zoom: 'Zoom',
            btn_ticket: 'Ticket',
            btn_download: 'Download PDF',
            btn_close: 'Close',
            qr_title: 'Your Entry Pass',
            general_access: 'General Access',
            empty_feedback: 'No feedback submitted yet.',
            swal_title: 'Cancel Booking?',
            swal_text: 'Are you sure you want to remove this pending booking?',
            swal_confirm: 'Yes, cancel it!'
        },
        visitor_notification: {
    "nav_title": "Notifications",
    "title": "Notifications Hub",
    "subtitle": "Stay updated with your campus visit alerts and area schedules.",
    "emergency_title": "Attention Required",
    "emergency_desc": "You have {count} unread critical notice updates.",
    "clear_all": "Clear All Messages",
    "mark_read": "Mark All as Read",
    "filter_all": "All Notices",
    "filter_unread": "Unread Only",
    "filter_important": "Critical Alerts",
    "empty_title": "All Clear!",
    "empty_desc": "No new notifications found at this time.",
    "confirm_delete": "Are you sure you want to delete this notification?",
    "confirm_clear": "Are you sure you want to permanently clear all notifications?",
    "suggested_slot": "Suggested Appointment Slot",
    "accept_rebook": "Rebook Now"
  },
  visitor_profile: {
    "title": "Visitor Profile",
    "subtitle": "View your account details below.",
    "read_only": "Read Only",
    "verified_notice": "Your account information is verified.",
    "first_name": "First Name",
    "last_name": "Last Name",
    "email": "Email Address",
    "phone": "Phone Number",
    "security_footer": "For security reasons, some fields cannot be edited."
  },
  visitor_settings: {
    "page_title": "Security Settings",
    "title": "Security",
    "subtitle": "Update your account password to keep your account secure.",
    "current_password": "Current Password",
    "new_password": "New Password",
    "confirm_password": "Confirm New Password",
    "placeholder_current": "Enter your current password",
    "placeholder_new": "Enter new password",
    "placeholder_confirm": "Confirm new password",
    "footer_note": "Ensure your account is using a long, random password to stay secure.",
    "btn_update": "Update Password",
    "btn_processing": "Updating...",
    "success_title": "Success!",
    "success_text": "Your password has been updated."
  },
    
        // ... existing keys
        guide_login: {
            title: 'Guide',
            portal: 'Portal',
            subtitle: 'Official Station Access',
            hall_label: 'Assigned Gallery Hall',
            hall_placeholder: 'Select your station',
            email_label: 'Professional Email',
            password_label: 'Security Key',
            remember: 'Remember this station',
            btn_access: 'Authorize Access',
            btn_verifying: 'Verifying...',
            back_link: 'Return to Main Gateway'
        },
        
  "guide_nav": {
    "no_hall": "No Hall Assigned",
    "management": "Management System",
    "bookings": "Bookings",
    "scanner": "Scanner",
    "feedbacks": "Feedbacks",
    "profile": "Profile",
    "security": "Settings"
  },
  "nav": {
    "overview": "Overview",
    "account": "Account",
    "station": "Current Station",
    "logout": "Logout"
  },
        "feedbacks_for_guide": {
    "title": "Feedbacks",
    "portal_label": "User Feedback Management Portal",
    "search_placeholder": "Search by name or message...",
    "delete_confirm": "Are you sure you want to delete this feedback?",
    "visitor": "Visitor",
    "received": "Received Date",
    "today": "Today",
    "no_feedback": "No feedback found for"
    
  },
  
  "guide_dashboard": {
    "monitor_portal": "Monitor Portal",
    "open_scanner": "Open Scanner",
    "total_bookings": "Total Bookings",
    "total_desc": "Total visitors assigned to this hall.",
    "arrived_today": "Arrived Today",
    "arrived_desc": "Visitors who have successfully checked in.",
    "live_log": "Live Booking Log",
    "table_type": "Type",
    "table_slot": "Slot",
    "table_status": "Status",
    "table_actions": "Actions",
    "btn_arrived": "Arrived",
    "btn_no_show": "No Show",
    "confirm_status": "Are you sure you want to mark this status as {status}?"
  },
  "statuses": {
    "arrived": "Arrived",
    "off-schedule": "Off-Schedule",
    "late": "Late",
    "no-show": "No Show",
    "missed": "Missed",
    "pending": "Pending",
    "approved": "Approved"
  },
  
  
        
        
        profile: {
            title: 'Account Profile',
            subtitle: 'View your registered personal information and contact details.',
            email: 'Email Address',
            phone: 'Phone Number',
            security_footer: 'Your information is protected by ACAGMS security protocols.'
        },
        settings: {
    title: "Settings",
    security: "Security",
    settings: "Settings",
    subtitle: "Manage your access credentials",
    update_password: "Update Password",
    password_desc: "Ensure your account is secure with a strong password.",
    current_password: "Current Password",
    new_password: "New Password",
    confirm_password: "Confirm Password",
    save: "Save Changes",
    saved: "Saved",
    processing: "Processing..."
},
guide_scanner: {
            title: "Entry Verification",
            start_camera: "Start Camera",
            ready: "Ready to scan...",
            scanning: "Scanning in progress...",
            access_granted: "Access Granted",
            access_denied: "Invalid Ticket"
        },
        guide_feedback: {
            title: "Feedbacks",
            feedbacks: "Feedbacks",
            subtitle: "Guide Portal • Monitoring Visitor Satisfaction",
            search: "Search visitor or comment...",
            visitor: "Visitor",
            received: "Received",
            today: "Today",
            empty: "No feedback found for",
            confirm_delete: "Remove this feedback from your list?"
        }
    },
    am: {
        nav1: {
            dashboard: "ዳሽቦርድ",
            new_booking: "አዲስ ማስያዣ",
            history: "ታሪክ",
            notifications: "ማሳወቂያ",
            feedback: "አስተያየት",
            profile: "መገለጫ",
            settings: "ቅንብር",
            logout: "ውጣ",
            main: "ዋና",
            preferences: "መለያ",
            overview: "አጠቃላይ",
        },
        
    register: {
        title: "መለያ ፍጠር",
        subtitle: "ለመጀመር ከዚህ በታች ያለውን መረጃ ይሙሉ",
        first_name: "መጀመሪያ ስም",
        last_name: "የአባት ስም",
        email: "የኢሜይል አድራሻ",
        phone: "ስልክ ቁጥር",
        visitor_category: "የጉብኝት አይነት",
        select_type: "አይነት ይምረጡ",
        local: "የሀገር ውስጥ ጎብኚ",
        foreign: "የውጭ ሀገር ጎብኚ",
        password: "የይለፍ ቃል",
        confirm_password: "የይለፍ ቃል ማረጋገጫ",
        register_btn: "አሁን ተመዝገብ",
        have_account: "ቀደም ሲል መለያ አለዎት?",
        sign_in: "ግባ",
        welcome_title: "ተሳክቷል!",
        welcome_text: "መለያዎ በስኬት ተፈጥሯል።",
        validation_failed: "የምዝገባ ስህተት",
        password_mismatch: "የገቡት የይለፍ ቃሎች አይዛመዱም።",
        first_name_error: "የመጀመሪያ ስም ፊደላትን ብቻ መያዝ አለበት (ያለ ክፍተት ወይም ቁጥር)።",
        last_name_error: "የአባት ስም ፊደላትን ብቻ መያዝ አለበት (ያለ ክፍተት ወይም ቁጥር)።",
        sidebar_title: "ወደ ማህበረሰባችን እንኳን በደህና መጡ",
        sidebar_desc: "የአዳማ ከተማን ይፋዊ ጋለሪ ለማየት፣ ጉብኝትዎን ለማስተዳደር እና የከተማዋን ሁነቶች ለመከታተል ዛሬውኑ ይመዝገቡ።"
    },
            admin: {
    "dashboard": "የአስተዳዳሪ ፓነል",
    "bookings": "ሁሉንም ማስያዣዎች",
    "halls": "የአዳራሽ ንብረቶች",
    "announcements": "ማስታወቂያዎች",
    "reports": "ሪፖርቶች",
    "guides": "የመመሪያ ሰራተኞች",
    "feedback": "ግብረመልስ",
    "gallery": "የፎቶ ማስተዳደሪያ",
    "profile": "የአስተዳዳሪ መገለጫ",
    "security": "የስርዓት ደህንነት",
    "system_health": "የስርዓት ሁኔታ",
    "logout": "ከስርዓት ውጣ"
  },
            admin_dashboard: {
            dashboard: "ዳሽቦርድ",
            overview: "አጠቃላይ",
            system_health: "የስርዓት ጤና እና የእውነተኛ ጊዜ ስታቲስቲክስ",
            protocol_optimal: "ፕሮቶኮል፡ በጥሩ ሁኔታ ላይ",
            total_visitors: "ጠቅላላ ጎብኝዎች",
            action_required: "እርምጃ ያስፈልጋል",
            active_guides: "ንቁ መመሪያዎች",
            command_center: "የትዕዛዝ ማዕከል",
            welcome_text: "እንኳን ወደ ACAGMS አስተዳደር ማዕከል በደህና መጡ። ጥያቄዎችን ያስተዳድሩ እና አፈጻጸምን ይገምግሙ።",
            execute_audit: "ኦዲት ያከናውኑ",
            uptime: "የስራ ጊዜ",
            load: "መጫን",
            system_logs: "የስርዓት ምዝግብ ማስታወሻዎች",
            view_all_logs: "ሁሉንም ምዝግብ ማስታወሻዎች ይመልከቱ"
        },
        
  
    "admin_Booking": {
        "registry_title": "የቀጠሮ መቆጣጠሪያ ማዕከል",
        "visitor": "ጎብኚ",
        "date": "ቀን",
        "slot": "ሰዓት",
        "status": "ሁኔታ",
        "status_change_title": "ሁኔታውን መቀየር",
        "status_confirm": "የዚህን ጎብኚ ሁኔታ ለመቀየር እርግጠኛ ነዎት?",
        "delete_title": "እርግጠኛ ነዎት?",
        "delete_warning": "ይህንን ድርጊት መቀልበስ አይችሉም!"
    },
    "action": {
        "search_placeholder": "በስም፣ በመታወቂያ ወይም በቀን ይፈልጉ",
        "update_confirm": "ማሻሻያውን ያረጋግጡ",
        "delete": "ሰርዝ",
        "actions": "ድርጊቶች"
    },
    "status": {
        "pending": "በሂደት ላይ",
        "approved": "ተቀባይነት አግኝቷል",
        "confirmed": "ተረጋግጧል",
        "arrived": "ደርሷል",
        "no_show": "አልመጣም",
        "cancelled": "ተሰርዟል",
        "rejected": "ውድቅ ሆኗል",
        "completed": "ተጠናቋል"
    },
        
 
  "gallery": {
        "title": "የከተማው ጋለሪ",
        "back_home": "ወደ መነሻ ተመለስ",
        "header_main": "የምስል",
        "header_sub": "መዝገብ",
        "description": "የአዳማን ቅርሶች እና እድገቶች የሚያሳይ ስብስብ።",
        "view_image": "ምስሉን ይመልከቱ"
    },
    "admin_feedbacks": {
    "title": "የጎብኝዎች አስተያየት",
    "visitor": "ጎብኚ",
    "review_mgmt": "የአስተያየት ማስተዳደሪያ",
    "submissions": "አስተያየቶች",
    "search_placeholder": "በስም፣ በኢሜይል ወይም በመልእክት ይፈልጉ...",
    "all_ratings": "ሁሉም ደረጃዎች",
    "stars": "ኮከቦች",
    "delete_confirm": "ይህንን አስተያየት መሰረዝ ይፈልጋሉ?",
    "no_email": "ኢሜይል የለም",
    "total_satisfied": "ጠቅላላ እርካታ",
    "natural_feedback": "መደበኛ አስተያየት",
    "total_unsatisfied": "ያልረኩ",
    "no_matches": "የሚዛመድ አስተያየት አልተገኘም"
  },
        halls: {
            title: "የጋለሪ አዳራሾች",
            subtitle: "የጋለሪ ቦታዎችን እና የኤግዚቢሽን ክፍሎችን ያስተዳድሩ",
            total: "ጠቅላላ አዳራሾች",
            add_new: "አዲስ አዳራሽ ጨምር",
            edit_hall: "አዳራሽ አሻሽል",
            name_label: "የአዳራሹ ስም",
            name_placeholder: "ምሳሌ፡ የአዳማ ታሪክ አዳራሽ",
            location_label: "ትክክለኛ ቦታ",
            location_placeholder: "ምሳሌ፡ 1ኛ ፎቅ፣ ብሎክ B",
            desc_label: "መግለጫ",
            desc_placeholder: "ስለ አዳራሹ ዝርዝር መረጃ ይጻፉ...",
            save: "አዳራሹን መዝግብ",
            update: "መረጃውን አዘምን",
            cancel: "ተመለስ",
            table_details: "ዝርዝር መረጃ",
            table_location: "ቦታ",
            table_actions: "ድርጊቶች",
            delete_confirm: "ይህንን አዳራሽ ለመሰረዝ እርግጠኛ ነዎት?",
            empty_title: "ምንም አዳራሽ አልተገኘም",
            empty_desc: "የመጀመሪያውን አዳራሽ በመፍጠር ይጀምሩ።"
        },  
        
    admin_announcement: {
        "page_title": "የድርጅት ማስጠንቀቂያ ስርዓት",
        "control_center": "የአስተዳዳሪ መቆጣጠሪያ ማዕከል",
        "broadcast_title": "የአደጋ ጊዜ ስርጭት",
        "broadcast_subtitle": "ሁሉንም የተመዘገቡ ጎብኝዎችን ወዲያውኑ ያሳውቁ።",
        "target_date": "የታለመው ቀን",
        "reschedule_date": "የተቀየረበት ቀን",
        "optional": "(አማራጭ)",
        "alert_title": "የማስጠንቀቂያው ርዕስ",
        "alert_placeholder": "ለምሳሌ፦ የጥገና ዝግ መረጃ",
        "message_content": "የመልዕክቱ ይዘት",
        "message_placeholder": "የማስታወቂያውን ዝርዝሮች ያስገቡ...",
        "broadcasting": "በማስተላለፍ ላይ...",
        "dispatch": "ማስጠንቀቂያውን ላክ",
        "preview": "ቀድሞ እይታ",
        "preview_default_title": "የማስታወቂያ ርዕስ",
        "preview_default_msg": "ተጠቃሚዎች ይህንን ማስጠንቀቂያ እንዴት እንደሚያዩት ቅድመ እይታ...",
        "auto_expire": "ከቀኑ በኋላ በራሱ ጊዜ ያልፋል",
        "smart_tool": "ብልህ መሣሪያ",
        "smart_tool_desc": "የቀጠሮ መቀየሪያ ቀን መጠቀም ስርዓቱ ለተጎዱ ጎብኝዎች አዲስ ጊዜ እንዲጠቁም ያስችለዋል።",
        "success": "መልዕክቱ በተሳካ ሁኔታ ተላልፏል!"
    },
    
  "admin_reports": {
    "title": "የአስተዳዳሪ ሪፖርቶች",
    "subtitle": "የስርዓት አፈጻጸም እና ግብረ መልስ",
    "export_pdf": "ፒዲኤፍ አውርድ",
    "print": "አትም",
    "registered_users": "የተመዘገቡ ተጠቃሚዎች",
    "total_bookings": "ጠቅላላ ቀጠሮዎች",
    "total_visitors": "ጠቅላላ ጎብኚዎች",
    "satisfied": "ረክተዋል",
    "unsatisfied": "አልረኩም",
    "filter_config": "ማጣሪያ ማዋቀር",
    "time_interval": "የጊዜ ክፍተት",
    "select_interval": "የጊዜ ክፍተት ይምረጡ",
    "weekly": "ሳምንታዊ",
    "monthly": "ወርሃዊ",
    "yearly": "ዓመታዊ",
    "chart_style": "የቻርት አይነት",
    "select_chart": "የቻርት አይነት ይምረጡ",
    "bar_chart": "የባር ቻርት",
    "line_chart": "የመስመር ቻርት",
    "pie_chart": "የፓይ ቻርት",
    "apply_filters": "ማጣሪያዎችን ተጠቀም",
    "updating": "በመዘመን ላይ...",
    "data_viz": "የውሂብ እይታ"
  },
    
    "admin_Gallery": {
        "page_title": "የምስል አስተዳደር",
        "gallery": "ማዕከለ ስዕላት",
        "studio": "ስቱዲዮ",
        "description": "ዲጂታል ፋይሎችዎን እና ቪዥዋል ታሪኮችን ያስተዳድሩ።",
        "delete_selection": "የተመረጡ ሰርዝ",
        "admin_mode": "አስተዳዳሪ ሁኔታ",
        "edit_asset": "ፋይል አርትዕ",
        "add_asset": "አዲስ ፋይል ጨምር",
        "cancel_edit": "አርትዕ ሰርዝ",
        "drag_images_here": "ምስሎችን እዚህ ይጎትቱ",
        "or": "ወይም",
        "browse_files": "ፋይሎችን ይምረጡ",
        "from_device": "ከመሣሪያ",
        "internal_title": "የውስጥ ርዕስ",
        "entry_name": "ስም...",
        "uploading": "በመላክ ላይ...",
        "update_asset": "ፋይል አዘምን",
        "publish_asset": "ፋይል አትም",
        "live_preview": "ቅድመ እይታ",
        "awaiting_content": "ይዘት በመጠበቅ ላይ",
        "untitled_asset": "ርዕስ የሌለው",
        "library_catalog": "የላይብረሪ ዝርዝር",
        "filter_title": "በርዕስ ፈልግ...",
        "no_assets": "ምንም ፋይል አልተገኘም።",
        "edit": "አርትዕ",
        "delete": "ሰርዝ",
        "enter_title": "እባክዎ ርዕስ ያስገቡ",
        "asset_updated": "ፋይል ተዘምኗል ✨",
        "image_published": "ምስል ታትሟል 🚀",
        "confirm_delete": "ይህን ፋይል በቋሚነት ማጥፋት ይፈልጋሉ?",
        "deleted_success": "በተሳካ ሁኔታ ተሰርዟል",
        "delete_selected": "የተመረጡ ሰርዝ",
        "bulk_complete": "ብዙ ስራ ተጠናቋል"
    },
    
  "admin_guides": {
    "title": "የመሪዎች አስተዳደር",
    "header": "የመሪዎች አስተዳደር ማዕከል",
    "sub_header": "የመሪዎች ስርአት አስተዳደር",
    "uploading": "እየጫነ ነው...",
    "bulkImport": "ጅምላ ጭነት",
    "total": "ጠቅላላ መሪዎች",
    "assigned": "የተመደቡ መሪዎች",
    "unassigned": "ያልተመደቡ መሪዎች",
    "register": "አዲስ መሪ ይመዝግቡ",
    "update": "መሪውን ያዘምኑ",
    "select": "ይምረጡ...",
    "male": "ወንድ",
    "female": "ሴት",
    "search": "በስም ወይም በኢሜይል ይፈልጉ...",
    "buttons": { "confirm": "ምዝገባ ያረጋግጡ", "save": "ለውጥ ያስቀምጡ" },
    "fields": { "name": "ሙሉ ስም", "email": "የኢሜይል አድራሻ", "phone": "ስልክ ቁጥር", "gender": "ጾታ", "hall": "አዳራሽ ይመድቡ" }
  },
        feedbacks: {
            title: 'የጎብኝዎች አስተያየት',
            total_bookings: 'ጠቅላላ ምዝገባዎች',
            good: 'ጥሩ አስተያየት',
            neutral: 'መካከለኛ አስተያየት',
            bad: 'መጥፎ አስተያየት',
            visitor: 'ጎብኝ',
            review_mgmt: 'የአስተያየት አስተዳደር',
            submissions: 'የገቡ አስተያየቶች',
            search_placeholder: 'በስም ወይም በመልእክት ፈልግ...',
            all_ratings: 'ሁሉም ደረጃዎች',
            stars: 'ኮከቦች',
            unknown_user: 'ያልታወቀ ተጠቃሚ',
            no_email: 'ኢሜይል የለም',
            delete_confirm: 'ይህንን አስተያየት ለማጥፋት እርግጠኛ ነዎት?',
            submitted: 'ገብቷል',
            no_found: 'ምንም አስተያየት አልተገኘም'
        },
        admin_profile: {
            title: "የፕሮፋይል አስተዳደር",
            avatar_title: "የአቫታር አስተዳደር",
            avatar_help: "ለተሻለ ውጤት ካሬ ምስል ይስቀሉ::",
            change_photo: "ፎቶ ቀይር",
            first_name: "ስም",
            last_name: "የአባት ስም",
            phone: "ስልክ ቁጥር",
            email: "ዋና ኢሜይል",
            save: "ለውጦችን አስቀምጥ",
            updating: "በማዘመን ላይ..."
        },
        admin_settings: {
            title: "የደህንነት ቅንብሮች",
            subtitle: "የአስተዳዳሪ መግቢያ ምስጢር ቃል ይቀይሩ",
            current_password: "ያሁኑ ምስጢር ቃል",
            new_password: "አዲስ ምስጢር ቃል",
            confirm_password: "አዲሱን ምስጢር ቃል ያረጋግጡ",
            update_btn: "መረጃውን አዘምን",
            updating_btn: "በማዘመን ላይ..."
        },
        system_status: {
            page_title: "የስርዓት ፕሮቶኮል",
            header: "የስርዓት ተገኝነት",
            title: "የመግቢያ ቁጥጥር",
            subtitle: "የ ACAGMS ፖርታል አጠቃላይ ተገኝነትን እዚህ ያስተዳድሩ::",
            mode: "ሁነታ",
            active: "ንቁ",
            maintenance: "ጥገና ላይ",
            inactive: "አይሰራም",
            save_btn: "ለውጦችን አስቀምጥ",
            updating_btn: "በማዘመን ላይ..."
        },
        


       
  "guide_nav": {
    "no_hall": "አዳራሽ አልተመደበም",
    "management": "የניהል ስርዓት",
    "bookings": "የቦታ ማስያዣዎች",
    "scanner": "ቃኚ (Scanner)",
    "feedbacks": "አስተያየቶች",
    "profile": "መገለጫ",
    "security": "ቅንብሮች"
  },
  "nav": {
    "overview": "አጠቃላይ እይታ",
    "account": "መለያ",
    "station": "የአሁኑ ጣቢያ",
    "logout": "ውጣ"
  },

  
  
  "guide_dashboard": {
    "monitor_portal": "የክትትል ፖርታል",
    "open_scanner": "ቃኚን ይክፈቱ",
    "total_bookings": "ጠቅላላ ማስያዣዎች",
    "total_desc": "ጠቅላላ የጎብኝዎች ማስያዣ ብዛት",
    "arrived_today": "ዛሬ የደረሱ",
    "arrived_desc": "የገቡ ጎብኝዎች ብዛት",
    "live_log": "የቀጥታ መረጃ",
    "live_monitoring": "ቅጽበታዊ ክትትል",
    "table_type": "ዓይነት",
    "table_slot": "ጊዜ",
    "table_status": "ሁኔታ",
    "table_actions": "ድርጊቶች",
    "empty_log": "ምንም ማስያዣ የለም",
    "confirm_status": "ሁኔታውን ወደ {status} ለመቀየር እርግጠኛ ነዎት?",
    "btn_arrived": "ደረሰ",
    "btn_no_show": "አልመጣም"
  },
  "statuses": {
    "arrived": "ደረሰ",
    "no-show": "አልመጣም",
    "approved": "ተቀባይነት አግኝቷል",
    "pending": "በሂደት ላይ",
    "late": "ዘግይቷል"
  },
        feedbacks_for_guide: {
            title: "አስተያየቶች",
            portal_label: "የመመሪያ ፖርታል • የጎብኝዎችን እርካታ መከታተያ",
            search_placeholder: "ጎብኝ ወይም አስተያየት ፈልግ...",
            received: "የደረሰበት ቀን",
            visitor: "ጎብኝ",
            no_feedback: "ምንም አስተያየት አልተገኘም ለ",
            delete_confirm: "ይህንን አስተያየት ከዝርዝርዎ ውስጥ ያስወግዱት?",
            today: "ዛሬ"
        },
        "guides_dashboard": {
    "page_title": "የመመሪያ ዳሽቦርድ",
    "monitor_portal": "የክትትል ፖርታል",
    "no_hall": "አዳራሽ የለም",
    "open_scanner": "ስካነር ክፈት",
    "total_bookings": "ጠቅላላ ቦታ ማስያዣ",
    "arrived_today": "ዛሬ የደረሱ",
    "live_log": "ቀጥታ መዝገብ",
    "type": "አይነት",
    "slot": "ሰዓት",
    "status": "ሁኔታ",
    "actions": "እርምጃ",
    "arrived": "ደርሷል",
    "no_show": "አልተገኘም",
    "empty_log": "ምንም መዝገብ የለም",
    "confirm_status": "ሁኔታን ወደ {status} መቀየር ይፈልጋሉ?"
  },
        
        profile: {
            title: 'የመገለጫ መረጃ',
            subtitle: 'የተመዘገቡ የግል መረጃዎችን እና የአድራሻ ዝርዝሮችን ይመልከቱ።',
            read_only: 'ለንባብ ብቻ',
            verified_notice: 'የመገለጫ መረጃዎ በምዝገባ ወቅት ተረጋግጧል። እነዚህን ዝርዝሮች ለማዘመን እባክዎን የአዳማ ከተማ አስተዳደር ቢሮን ይጎብኙ ወይም ድጋፍ ሰጪዎችን ያነጋግሩ።',
            first_name: 'ስም',
            last_name: 'የአባት ስም',
            email: 'ኢሜይል አድራሻ',
            phone: 'ስልክ ቁጥር',
            security_footer: 'መረጃዎ በACAGMS የደህንነት ፕሮቶኮሎች የተጠበቀ ነው።'
        },
        settings: {
    title: "ቅንብሮች",
    security: "ደህንነት",
    settings: "ቅንብሮች",
    subtitle: "የመግቢያ መረጃዎን ያስተዳድሩ",
    update_password: "የይለፍ ቃል አዘምን",
    password_desc: "መለያዎን በጠንካራ የይለፍ ቃል ይጠብቁ።",
    current_password: "የአሁኑ የይለፍ ቃል",
    new_password: "አዲስ የይለፍ ቃል",
    confirm_password: "የይለፍ ቃል አረጋግጥ",
    save: "አስቀምጥ",
    saved: "ተቀምጧል",
    processing: "በመሰራት ላይ..."
},
        security: {
            title: "የመለያ ደህንነት",
            subtitle: "መለያዎን ይጠብቁ እና የይለፍ ቃልዎን ያስተዳድሩ።",
            page_title: "የደህንነት ቅንብሮች",
            current_password: "የአሁኑ የይለፍ ቃል",
            new_password: "አዲስ የይለፍ ቃል",
            confirm_password: "የይለፍ ቃሉን ያረጋግጡ",
            placeholder_current: "የአሁኑን የይለፍ ቃል ያስገቡ",
            placeholder_new: "ቢያንስ 8 ቁምፊዎች",
            placeholder_confirm: "አዲሱን የይለፍ ቃል ይድገሙ",
            footer_note: "መረጃዎ በACAGMS የደህንነት ፕሮቶኮሎች የተጠበቀ ነው።",
            btn_update: "የይለፍ ቃል አዘምን",
            btn_processing: "በመሰራት ላይ...",
            success_title: "ደህንነት ተዘምኗል",
            success_text: "የይለፍ ቃልዎ በተሳካ ሁኔታ ተቀይሯል።"
        },
       visitor_dashboard: {
    "nav_title": "ዳሽቦርድ",
    "welcome_back": "እንኳን ደህና መጡ",
    "hello": "ሰላም",
    "explore_desc": "የቦታ ማስያዣ አማራጮችዎን ያስሱ እና የያዙትን ቦታዎች ያስተዳድሩ!",
    "btn_book": "አዲስ ቦታ አስይዝ",
    "btn_history": "የቦታ ማስያዝ ታሪክ",
    "pending_bookings": "በተጠባባቂ ላይ ያሉ",
    "approved_bookings": "የተፈቀዱ ቦታዎች",
    "recent_bookings": "የቅርብ ጊዜ ቦታ ማስያዞች",
    "view_all": "ሁሉንም አሳይ",
    "table_hall": "አዳራሽ",
    "table_date": "ቀን",
    "table_status": "ሁኔታ",
    "table_notes": "ማስታወሻዎች",
    "no_bookings_found": "ምንም የተያዘ ቦታ አልተገኘም",
    "no_bookings_desc": "እስካሁን ምንም ዓይነት የኤግዚቢሽን ማዕከል ቦታ አላስያዙም።",
    "create_booking": "ቦታ አስይዝ"
  },
        visitor_booking: {
    title: 'አዲስ ቦታ ማስያዝ',
    
    // Steps
    step_select_hall: 'አዳራሽ መምረጥ',
    step_visitor_type: 'የጎብኚ ዓይነት',
    step_schedule: 'ቀጠሮ ማስያዝ',
    
    // Headers & Subtitles
    header_choose_halls: 'አዲስ ቦታ ለመያዝ አዳራሽ ይምረጡ',
    subtitle_choose_halls: 'ለመቀጠል አንድ ወይም ከዚያ በላይ አዳራሾችን ይምረጡ',
    header_visitor_type: 'የጎብኚውን ዓይነት ይምረጡ',
    header_schedule: 'የጉብኝት ቀጠሮ',
    
    // Categories
    category_normal: 'መደበኛ ጎብኚ',
    category_vip: 'ክቡር ጎብኚ (VIP)',
    
    // Labels
    label_date: 'የጉብኝት ቀን',
    label_visitor_count: 'የጎብኚዎች ብዛት ስንት ነው?',
    label_upload_letter: 'የድጋፍ ደብዳቤ ይጫኑ',
    label_time_slot: 'የጉብኝት ሰዓት',
    
    // Slots
    slot_early_morning: 'ማለዳ',
    slot_mid_morning: 'ረፋድ',
    slot_late_morning: 'ከሰዓት በፊት',
    slot_early_afternoon: 'ከሰዓት በኋላ',
    slot_mid_afternoon: 'ወደ ማምሻው',
    slot_late_afternoon: 'ሲመሽ',
    
    // Buttons
    btn_continue: 'ቀጥል',
    btn_back_halls: 'ወደ აዳራሾች ምርጫ ይመለሱ',
    btn_back: 'ወደ ኋላ',
    btn_confirm: 'ቦታ አስይዝ',
    btn_processing: 'በማካሄድ ላይ...',
    
    // Alerts & Alerts texts
    alert_restricted_title: 'ቦታ ማስያዝ አልተፈቀደም',
    alert_select_hall_title: 'አዳራሽ ይምረጡ',
    alert_select_hall_text: 'እባክዎን ቢያንስ አንድ አዳራሽ ይምረጡ',
    alert_weekend_title: 'ቅዳሜና እሁድ አይፈቀድም',
    alert_weekend_text: 'ቦታ ማስያዝ የሚቻለው ከሰኞ እስከ አርብ ባሉት ቀናት ብቻ ነው',
    alert_missing_doc_title: 'ማስረጃ አልተገኘም',
    alert_missing_doc_text: 'ለቪአይፒ (VIP) ምዝገባ ይፋዊ የድጋፍ ደብዳቤ ያስፈልጋል',
    alert_select_slot_title: 'የጉብኝት ሰዓት ይምረጡ',
    alert_select_slot_text: 'እባክዎን ማረጋገጫ ከመስጠትዎ በፊት የሰዓት አማራጭ ይምረጡ',
    alert_success_text: 'ቦታው በስኬት ተይዟል!',
    alert_failed_title: 'ጥያቄው አልተሳካም',
    alert_failed_text: 'እባክዎን ያስገቡትን መረጃ በትክክል መሆኑን ያረጋግጡ'
},
        login: {
            title: "ይግቡ",
            subtitle: "ዲጂታል የመንግስት አገልግሎቶች",
            welcome: "እንኳን ደህና መጡ",
            description: "መለያ ካለዎት እባክዎ ወደ ዳሽቦርዱ ለመቀጠል ይግቡ",
            email_label: "ኢሜይል አድራሻ",
            brand_city: "የአዳማ ከተማ",
            brand_admin: "አስተዳደር",
            sidebar_subtitle: "የጋለሪ አስተዳደር ስርዓት",
            email_placeholder: "ኢሜይልዎን ያስገቡ",
            password_label: "የይለፍ ቃል",
            forgot_password: "የይለፍ ቃል ረስተዋል?",
            remember_me: "አስታውሰኝ",
            sign_in_btn: "ወደ ዳሽቦርድ ይግቡ",
            authenticating: "በማረጋገጥ ላይ...",
            no_account: "መለያ የለዎትም?",
            sign_up: "ይመዝገቡ",
            footer: "© 2026 የአዳማ ከተማ አስተዳደር - ስማርት ሲቲ ኢኒሼቲቭ"
        },
        history: {
            qr_pass: 'QR ፓስ',
            actions: 'ድርጊቶች',
            zoom: 'አሳድግ',
            btn_ticket: 'ቲኬት',
            btn_download: 'ፒዲኤፍ አውርድ',
            btn_close: 'ዝጋ',
            qr_title: 'የመግቢያ መታወቂያ',
            general_access: 'መደበኛ ጉብኝት',
            empty_feedback: 'ምንም አስተያየት አልተሰጠም።',
            swal_title: 'ቦታ ማስያዣ ይሠረዝ?',
            swal_text: 'ይህን በጥበቃ ላይ ያለ ቦታ ማስያዣ መሰረዝዎን እርግጠኛ ነዎት?',
            swal_confirm: 'አዎ ሰርዝ!'
        },
        visitor_notification: {
    "nav_title": "ማሳወቂያዎች",
    "title": "የማሳወቂያዎች ማዕከል",
    "subtitle": "ስለ ካምፓስ ጉብኝትዎ እና ስለ አካባቢው መርሃግብሮች ወቅታዊ መረጃ ያግኙ።",
    "emergency_title": "ትኩረት ያስፈልጋል",
    "emergency_desc": "ያልተነበቡ {count} ወሳኝ የማሳወቂያ መልእክቶች አሉዎት።",
    "clear_all": "ሁሉንም አጽዳ",
    "mark_read": "ሁሉንም እንደተነበበ አድርግ",
    "filter_all": "ሁሉም ማሳወቂያዎች",
    "filter_unread": "ያልተነበቡ ብቻ",
    "filter_important": "አስቸኳይ ማንቂያዎች",
    "empty_title": "ምንም ማሳወቂያ የለም!",
    "empty_desc": "በዚህ ጊዜ ምንም አዲስ ማሳወቂያ አልተገኘም።",
    "confirm_delete": "ይህን ማሳወቂያ መሰረዝ መፈለግዎን እርግጠኛ ነዎት?",
    "confirm_clear": "ሁሉንም ማሳወቂያዎች በቋሚነት ማጽዳት መፈለግዎን እርግጠኛ ነዎት?",
    "suggested_slot": "የቀረበው የቀጠሮ ሰዓት",
    "accept_rebook": "አሁን ቀጠሮ ይያዙ"
  },
        visitor_feedback: {
      "title": "አስተያየት ያስገቡ",
      "header": "የእርስዎን አስተያየት ይስጡ",
      "lock_title": "አስተያየት መስጫው ተቆልፏል",
      "lock_text": "እባክዎን መጀመሪያ አዳራሾችን ይጎብኙ ከዚያ አስተያየት መላክ ይችላሉ።",
      "btn_dashboard": "ወደ ዳሽቦርድ ይመለሱ",
      "type_general": "አጠቃላይ አስተያየት",
      "type_hall": "የአዳራሽ አስተያየት",
      "label_hall": "አዳራሽ ይምረጡ",
      "placeholder_hall": "የጎበኙትን አዳራሽ ይምረጡ",
      "label_subject": "ርዕስ",
      "placeholder_subject": "የአስተያየትዎ ዋና ርዕስ ምንድን ነው?",
      "label_sentiment": "የልምድ ምድብ",
      "opt_satisfaction": "እርካታ",
      "opt_neutral": "መካከለኛ",
      "opt_unsatisfactory": "ያልተደሰቱበት",
      "label_rating": "የደረጃ አሰጣጥ",
      "label_message": "ዝርዝር የአስተያየት መልዕክት",
      "placeholder_message": "ስለ ንጽህና ወይም ልዩ ልምዶችዎ ዝርዝር መረጃ እዚህ ያጋሩ...",
      "btn_add_photo": "ፎቶ አክል",
      "upload_hint": "ከፍተኛ 3MB, JPG/PNG/WEBP",
      "btn_cancel": "ሰርዝ",
      "btn_submit": "አስተያየት አስገቡ",
      "sending": "በመላክ ላይ...",
      "error_title": "ስህተት",
      "error_max_images": "ቢበዛ 3 ምስሎችን ብቻ መጫን ይችላሉ",
      "error_format": "የማይደገፍ የምስል አይነት ነው።",
      "error_size": "በጣም ትልቅ ነው። ከፍተኛው መጠን 3MB ነው።",
      "error_gibberish_title": "መልዕክትዎን ይፈትሹ",
      "error_gibberish_text": "ያስገቡት መልዕክት ግልጽ ያልሆኑ ቃላትን ይዟል። እባክዎን ትክክለኛ ፅሁፍ ያስገቡ።",
      "success_title": "እናመሰግናለን!",
      "success_text": "አስተያየትዎ በተሳካ ሁኔታ ተልኳል።"
    },
    visitor_profile: {
    "title": "የጎብኚ መገለጫ",
    "subtitle": "የመለያ ዝርዝሮችዎን ከዚህ በታች ይመልከቱ።",
    "read_only": "ለማንበብ ብቻ",
    "verified_notice": "የመለያዎ መረጃ ተረጋግጧል።",
    "first_name": "የመጀመሪያ ስም",
    "last_name": "የአባት ስም",
    "email": "ኢሜይል",
    "phone": "ስልክ ቁጥር",
    "security_footer": "ለደህንነት ሲባል አንዳንድ መረጃዎች ሊቀየሩ አይችሉም።"
  },
visitor_settings: {
    "page_title": "የደህንነት ቅንብሮች",
    "title": "ደህንነት",
    "subtitle": "መለያዎ ደህንነቱ የተጠበቀ እንዲሆን የይለፍ ቃልዎን ያዘምኑ።",
    "current_password": "የአሁኑ የይለፍ ቃል",
    "new_password": "አዲስ የይለፍ ቃል",
    "confirm_password": "አዲሱን የይለፍ ቃል ያረጋግጡ",
    "placeholder_current": "የአሁኑን የይለፍ ቃል ያስገቡ",
    "placeholder_new": "አዲስ የይለፍ ቃል ያስገቡ",
    "placeholder_confirm": "አዲሱን የይለፍ ቃል ደግመው ያስገቡ",
    "footer_note": "መለያዎ ደህንነቱ የተጠበቀ እንዲሆን ረጅም እና ግራ የሚያጋባ የይለፍ ቃል ይጠቀሙ።",
    "btn_update": "የይለፍ ቃል ያዘምኑ",
    "btn_processing": "በመዘመን ላይ...",
    "success_title": "ተሳክቷል!",
    "success_text": "የይለፍ ቃልዎ ተዘምኗል።"
  },
        // ... existing keys
        guide_login: {
            title: 'የመመሪያ',
            portal: 'ፖርታል',
            subtitle: 'ይፋዊ የጣቢያ መግቢያ',
            hall_label: 'የተመደበው የጋለሪ አዳራሽ',
            hall_placeholder: 'ጣቢያዎን ይምረጡ',
            email_label: 'የስራ ኢሜይል',
            password_label: 'የደህንነት ቁልፍ',
            remember: 'ይህንን ጣቢያ አስታውስ',
            btn_access: 'ፈቃድ አረጋግጥ',
            btn_verifying: 'በማረጋገጥ ላይ...',
            back_link: 'ወደ ዋናው በር ተመለስ'
        },
        "feedbacks_for_guide": {
    "title": "አስተያየቶች",
    "portal_label": "የአስተያየት አስተዳደር ገጽ",
    "search_placeholder": "በስም ወይም በአስተያየት ይፈልጉ...",
    "delete_confirm": "ይህንን አስተያየት መሰረዝ ይፈልጋሉ?",
    "visitor": "ጎብኚ",
    "received": "የተቀበለበት ቀን",
    "today": "ዛሬ",
    "no_feedback": "ምንም አስተያየት አልተገኘም ለ"
  },
        nav: {
            overview: 'አጠቃላይ እይታ',
            account: 'መለያ',
            station: 'የአሁኑ ጣቢያ',
            logout: 'ውጣ',
        },
        guide_nav: {
            management: 'የመመሪያ አስተዳደር',
            bookings: 'ቦታ ማስያዣ',
            scanner: 'QR ስካነር',
            feedbacks: 'አስተያየቶች',
            profile: 'መገለጫ',
            security: 'ደህንነት',
            no_hall: 'ምንም አዳራሽ አልተመደበም',
        },
        
        guide_scanner: {
            title: "የመግቢያ ማረጋገጫ",
            start_camera: "ካሜራ አስጀምር",
            ready: "ለመቃኘት ዝግጁ...",
            scanning: "በመቃኘት ላይ...",
            access_granted: "ተፈቅዷል",
            access_denied: "ትኬቱ ትክክል አይደለም"
        },
        profile: {
            subtitle: 'የግል መረጃዎችን ይመልከቱ',
            email: 'ኢሜይል',
            phone: 'ስልክ',
            security_footer: 'መረጃዎ ተጠብቆ ነው'
        },
        
  "guide_dashboard": {
    "monitor_portal": "የክትትል ፖርታል",
    "open_scanner": "ስካነር ይክፈቱ",
    "total_bookings": "ጠቅላላ ማስያዣዎች",
    "total_desc": "ለዚህ አዳራሽ የተመደቡ ጎብኝዎች።",
    "arrived_today": "ዛሬ የደረሱ",
    "arrived_desc": "በስኬት የገቡ ጎብኝዎች።",
    "live_log": "የቀጥታ ምዝገባ",
    "table_type": "ዓይነት",
    "table_slot": "ጊዜ",
    "table_status": "ሁኔታ",
    "table_actions": "ድርጊቶች",
    "btn_arrived": "ደረሱ",
    "btn_no_show": "አልመጡም",
    "confirm_status": "ሁኔታውን ወደ {status} ለመቀየር እርግጠኛ ነዎት?"
  },
  "statuses": {
    "arrived": "ደረሱ",
    "off-schedule": "ከጊዜ ውጪ",
    "late": "ረፍደዋል",
    "no-show": "አልመጡም",
    "missed": "አምልጠዋል",
    "pending": "በሂደት ላይ",
    "approved": "ተፈቅዷል"
  },
  
    
        guide_feedback: {
            title: "አስተያየቶች",
            feedbacks: "አስተያየቶች",
            subtitle: "የመመሪያ ፖርታል",
            search: "ጎብኚ ወይም አስተያየት ፈልግ...",
            visitor: "ጎብኚ",
            received: "ተቀባ",
            today: "ዛሬ",
            empty: "ምንም አልተገኘም",
            confirm_delete: "ይህን አስተያየት ማስወገድ ይፈልጋሉ?"
        }
    },

    or: {
        nav1: {
            dashboard: "Dabsidii",
            new_booking: "Qabannaa Haaraa",
            history: "Seenaa",
            notifications: "Beeksisa",
            feedback: "Yaada",
            profile: "Profile",
            settings: "Sajataa",
            logout: "Ba’i",
            main: "Gara",
            preferences: "Account",
            overview: "Ilaalcha",
        },
    register: {
        title: "Akkaawuntii Uumi",
        subtitle: "Eegaluuf bal'ina odeeffannoo armaan gadii guuti",
        first_name: "Maqaa Jalqabaa",
        last_name: "Maqaa Abbaa",
        email: "Teessoo Imeelii",
        phone: "Lakkofsa Bilbilaa",
        visitor_category: "Gosa Daawwataa",
        select_type: "Gosa Filadhu",
        local: "Daawwataa Naannoo",
        foreign: "Daawwataa Alaa",
        password: "Jecha Icchitii",
        confirm_password: "Jecha Icchitii Mirkaneessi",
        register_btn: "Amma Galmaayi",
        have_account: "Duraan akkaawuntii qabduu?",
        sign_in: "Seeni",
        welcome_title: "Milkaa'ina!",
        welcome_text: "Akkaawuntiin keessan milkaa'inaan uumameera.",
        validation_failed: "Dogoggora Galmee",
        password_mismatch: "Jechi icchitii wal hin qixxaanne.",
        first_name_error: "Maqaan jalqabaa qubee qofa qabaachuu qaba (iddoo duwwaa ykn lakkofsa malee).",
        last_name_error: "Maqaan abbaa qubee qofa qabaachuu qaba (iddoo duwwaa ykn lakkofsa malee).",
        sidebar_title: "Gara Hawaasa Keenyaatti Baga Gammaddan",
        sidebar_desc: "Galaree ragaa bulchiinsa magaalaa Adaamaa argachuuf, daawwanna keessan bulchuufi waa'ee dhimmoota magaalaa hordofuuf har'uma galmaa'aa."
    } ,// Closes register
           admin: {
    "dashboard": "paanaalii Bulchiinsaa",
    "bookings": "Qabannoowwan Hunda",
    "halls": "Qabeenya Galma",
    "announcements": "Beeksisa",
    "reports": "Gabaasa",
    "guides": "Hojjattoota Qajeelchaa",
    "feedback": "Yaada",
    "gallery": "Bulchiinsa Suuraa",
    "profile": "Saagiinsa Bulchiinsaa",
    "security": "Nageenya Sirnaa",
    "system_health": "Fayyaa Sirnaa",
    "logout": "Sirna Keessaa Ba'i"
  },
            admin_dashboard: {
            dashboard: "Daashboordii",
            overview: "Waliigala",
            system_health: "Fayyaa Sirnaa fi Istaatistiiksii Yeroo Real",
            protocol_optimal: "Pirootokoolii: Gaarii",
            total_visitors: "Baay'ina Daawwattootaa",
            action_required: "Tarkaanfii Barbaachisaa",
            active_guides: "Qajeelchitoota Hojirra Jiran",
            command_center: "Wiirtuu Ajajaa",
            welcome_text: "Gara wiirtuu bulchiinsa ACAGMS tti baga nagaan dhuftan. Gaaffiwwan bulchuun akkasumas raawwii odiit godhaa.",
            execute_audit: "Odiitii Raawwadhu",
            uptime: "Yeroo Hojii",
            load: "Loodii",
            system_logs: "Galmee Sirnaa",
            view_all_logs: "Galmeewwan Hunda Ilaali"
        },
    
  
    "admin_Booking": {
        "registry_title": "Qajeelcha To'annoo Qabxii",
        "visitor": "Daawwataa",
        "date": "Guyyaa",
        "slot": "Sa'aatii",
        "status": "Haala",
        "status_change_title": "Haala jijjiiri",
        "status_confirm": "Haala daawwataa kana jijjiiruu keetti mirkanaa'aadha?",
        "delete_title": "Mirkaneessi?",
        "delete_warning": "Gocha kana deebisuu hin dandeessu!"
    },
    "action": {
        "search_placeholder": "Maqaa, ID ykn guyyaan barbaadi",
        "update_confirm": "Jijjiirama mirkaneessi",
        "delete": "Haqi",
        "actions": "Gochoota"
    },
    "status": {
        "pending": "Itti fufa jira",
        "approved": "Hayyamameera",
        "confirmed": "Mirkana'eera",
        "arrived": "Ga'eera",
        "no_show": "Hin dhufe",
        "cancelled": "Haqeera",
        "rejected": "Didameera",
        "completed": "Xumurameera"
    },
  
  "gallery": {
        "title": "Gaalarii Magaalaa",
        "back_home": "Gara Manaatti",
        "header_main": "Kuusaa",
        "header_sub": "Fakkii",
        "description": "Hambaalee fi guddina magaalaa Adaamaa kan agarsiisu.",
        "view_image": "Fakkii Ilaali"
    },
    "admin_feedbacks": {
    "title": "Yaada Keessummootaa",
    "visitor": "Keessummaa",
    "review_mgmt": "Bulchiinsa Yaadaa",
    "submissions": "yaada galfame",
    "search_placeholder": "Maqaa, iimeelii ykn ergaadhaan barbaadi...",
    "all_ratings": "Sadarkaa Hundaa",
    "stars": "Urjii",
    "delete_confirm": "Dhugumatti yaada kana haquu barbaaddaa?",
    "no_email": "Iimeeliin hin jiru",
    "total_satisfied": "Gammachuu Guutuu",
    "natural_feedback": "Yaada Giddu-galeessaa",
    "total_unsatisfied": "Yaada Hin Gammanne",
    "no_matches": "Yaada barbaaddan hin argamne"
  },
  
        halls: {
            title: "Galmawwan Gaalarii",
            subtitle: "Bakka galmawwan gaalarii fi kutaalee agarsiisaa bulchaa",
            total: "Waliigala Galmawwan",
            add_new: "Galma Haaraa Dabali",
            edit_hall: "Galma Haaromsi",
            name_label: "Maqaa Galmaa",
            name_placeholder: "fkn. Galma Seenaa Adaamaa",
            location_label: "Bakka Itti Argamu",
            location_placeholder: "fkn. Floor 1, Block B",
            desc_label: "Ibsa",
            desc_placeholder: "Waa’ee galma kanaa ibsaa...",
            save: "Galma Galmeessi",
            update: "Galma Haaromsi",
            cancel: "Dhiisi",
            table_details: "Odeeffannoo Galmaa",
            table_location: "Bakka",
            table_actions: "Gochaawwan",
            delete_confirm: "Galma kana haquu akka barbaaddu mirkaneeffatteettaa?",
            empty_title: "Galmi argame hin jiru",
            empty_desc: "Galma gaalarii keessan isa jalqabaa uumuun jalqabaa."
        },
        
    admin_announcement: {
        "page_title": "Siri Alartii Intarppiraayizii",
        "control_center": "Giddu-gala To'annoo Admin",
        "broadcast_title": "Tamsaasa Ariifachiisaa",
        "broadcast_subtitle": "Daawwatoota galmaa'an hunda yeroodhumaan beeksisi.",
        "target_date": "Guyyaa Targetii",
        "reschedule_date": "Guyyaa Haqamee",
        "optional": "(Filannoo)",
        "alert_title": "Mata-duree Alartii",
        "alert_placeholder": "fkn, Beeksisa Cufiinsaa Maintenance",
        "message_content": "Qabiyyee Ergaa",
        "message_placeholder": "Bal'ina beeksisaa galchi...",
        "broadcasting": "Tamsaasaa jira...",
        "dispatch": "Alartii Ergi",
        "preview": "Dur-argii",
        "preview_default_title": "Mata-duree Beeksisaa",
        "preview_default_msg": "Akkaataa itti tajaajilamtoonni alartii kana argu danda'an...",
        "auto_expire": "Guyyaa booda ofumaan ni bada",
        "smart_tool": "Meeshaa Smart",
        "smart_tool_desc": "Guyyaa 'Reschedule' fayyadamuun sirni kun daawwattootaaf yeroo haaraa akka gorsu taasisa.",
        "success": "Tamsaasni milkiin ergameera!"
    },
     
  "admin_reports": {
    "title": "Gabaasa Bulchiinsa",
    "subtitle": "Gocha Sirnaa fi Yaada",
    "export_pdf": "PDF ergi",
    "print": "Maxansi",
    "registered_users": "Fayyadamtoota Galmaa'an",
    "total_bookings": "Qabxii Waliigalaa",
    "total_visitors": "Daawwattoota Waliigalaa",
    "satisfied": "Gammadaniiru",
    "unsatisfied": "Hin gammanne",
    "filter_config": "Qindeessaa Filannoo",
    "time_interval": "Yeroo",
    "select_interval": "Yeroo filadhu",
    "weekly": "Torbanitti",
    "monthly": "Ji'a ji'aan",
    "yearly": "Waggootti",
    "chart_style": "Akkaataa Chartii",
    "select_chart": "Akkaataa chartii filadhu",
    "bar_chart": "Chartii Bar",
    "line_chart": "Chartii Sararaa",
    "pie_chart": "Chartii Pie",
    "apply_filters": "Filannoo Hojii Irra Oolchi",
    "updating": "Haaraa itti fufa...",
    "data_viz": "Ilaalcha Odeeffannoo"
  },
    
    "admin_Gallery": {
        "page_title": "Bulchiinsa Galmee",
        "gallery": "Galmee",
        "studio": "Istuudiyoo",
        "description": "Faayiloota dijitaalaa fi suuraa keessan bulchi.",
        "delete_selection": "Kan Filataman Haqi",
        "admin_mode": "Haala Admin",
        "edit_asset": "Faayilii Sirreessi",
        "add_asset": "Faayilii Haaraa Dabaluu",
        "cancel_edit": "Sirreessuu Dhiisi",
        "drag_images_here": "Suuraalee asitti harkisi",
        "or": "ykn",
        "browse_files": "faayiloota filadhu",
        "from_device": "meeshaa irraa",
        "internal_title": "Mata Duree",
        "entry_name": "Maqaa galchaa...",
        "uploading": "OLKAA'AA JIRA...",
        "update_asset": "FAAYILII HAAROMSI",
        "publish_asset": "FAAYILII MAXXANSI",
        "live_preview": "Dursee Ilaali",
        "awaiting_content": "Qabiyyee Eeggachaa Jira",
        "untitled_asset": "Faayilii Maqaa Hin Qabne",
        "library_catalog": "Kuusaa Galmee",
        "filter_title": "Mata dureen barbaadi...",
        "no_assets": "Faayilli mootummaa hin argamne.",
        "edit": "Sirreessi",
        "delete": "Haqi",
        "enter_title": "Maqaa galchi",
        "asset_updated": "Faayilli haaromfameera ✨",
        "image_published": "Suuraan maxxanfameera 🚀",
        "confirm_delete": "Faayila kana keessaa haquu barbaaddaa?",
        "deleted_success": "Milkaa’inaan haqameera",
        "delete_selected": "Kan filataman haqi",
        "bulk_complete": "Hojiin walitti qabame xumurameera"
    },
    
  "admin_guides": {
    "title": "Bulchiinsa Qajeelchitootaa",
    "header": "IDDOO BULCHIINSA QAJEELCHITOOTAA",
    "sub_header": "Bulchiinsa qajeelchitootaa sirna guutuu",
    "uploading": "Fe'aa jira...",
    "bulkImport": "Galchuuf (Bulk)",
    "total": "Qajeelchitoota Hunda",
    "assigned": "Qajeelchitoota Ramadaman",
    "unassigned": "Qajeelchitoota hin ramadamne",
    "register": "Qajeelchituu Haaraa Galchi",
    "update": "Qajeelchituu Haaromsi",
    "select": "Filadhu...",
    "male": "Dhiira",
    "female": "Dubartii",
    "search": "Maqaa ykn email barbaadi...",
    "buttons": { "confirm": "Galmeessi", "save": "Jijjiirama Olkaa'i" },
    "fields": { "name": "Maqaa Guutuu", "email": "Email", "phone": "Lakkoofsa Bilbilaa", "gender": "Saala", "hall": "Hallii Ramadi" }
  },
        feedbacks: {
            title: 'Yaada Daawwattootaa',
            total_bookings: 'Waliigala Qabannaa',
            good: 'Yaada Gaarii',
            neutral: 'Yaada Giddu-galeessa',
            bad: 'Yaada Gadhee',
            visitor: 'Daawwataa',
            review_mgmt: 'Bulchiinsa Yaadaa',
            submissions: 'Yaadota Kennaman',
            search_placeholder: 'Barbaadi...',
            all_ratings: 'Sadarkaa Hunda',
            stars: 'Urjiiwwan',
            unknown_user: 'Nama hin beekamne',
            no_email: 'Imeelii hin qabu',
            delete_confirm: 'Haquu barbaadduu?',
            submitted: 'Kan Ergame',
            no_found: 'Yaanni argame hin jiru'
        },
        
       
  "guide_nav": {
    "no_hall": "Halli hin ramadamne",
    "management": "Sirna Bulchiinsa",
    "bookings": "Qabxiiwwan",
    "scanner": "Skaanaara",
    "feedbacks": "Yaada",
    "profile": "Pirofaayilii",
    "security": "Qindiiwwan"
  },
  "nav": {
    "overview": "Guddattoota",
    "account": "akaawuntii",
    "station": "Buufata Ammaa",
    "logout": "Ba'i"
  },
  
  
  "guide_dashboard": {
    "monitor_portal": "Daawwannaa Qabxii",
    "open_scanner": "Skaanaara Banii",
    "total_bookings": "Qabxii Waliigalaa",
    "total_desc": "Hanga ammaa kan galmaa'an.",
    "arrived_today": "Har'a Kan Dhuftan",
    "arrived_desc": "Kan galmaa'anii darban.",
    "live_log": "Logii Qabxii",
    "table_type": "Gosa",
    "table_slot": "Yeroo",
    "table_status": "Haala",
    "table_actions": "Gocha",
    "btn_arrived": "Dhufeera",
    "btn_no_show": "Hin Dhufne",
    "confirm_status": "Haalli isaa {status} akka ta'u mirkaneessi?"
  },
  "statuses": {
    "arrived": "Dhufeera",
    "off-schedule": "Yeroo alaa",
    "late": "Baree",
    "no-show": "Hin Dhufne",
    "missed": "Darbeera",
    "pending": "Eeggachaa",
    "approved": "Mirkanaa'e"
  },
  
  "feedbacks_for_guide": {
    "title": "Yaada",
    "portal_label": "Garaa bulchiinsa yaadaa",
    "search_placeholder": "Maqaa ykn yaada barbaadi...",
    "delete_confirm": "Yaada kana haquu ni barbaadda?",
    "visitor": "Daawwataa",
    "received": "Guyyaa fudhatame",
    "today": "Har'a",
    "no_feedback": "Yaada hin argamneef"
  },
  
           
        admin_profile: {
            title: "Bulchiinsa Piroofayilii",
            avatar_title: "Bulchiinsa Avataaraa",
            avatar_help: "Bu'aa gaariidhaaf fakkii Iskuweerii olkaa'aa.",
            change_photo: "Suuraa Jijjiiri",
            first_name: "Maqaa",
            last_name: "Maqaa Abbaa",
            phone: "Lakk. Bilbilaa",
            email: "Imeelii",
            save: "Jijjiirama Olkaa'i",
            updating: "Haaromsaa jira..."
        },
        admin_settings: {
            title: "Sajeeffama Nageenyaa",
            subtitle: "Jecha icciitii bulchiinsaa jijjiiri",
            current_password: "Jecha Icciitii Ammee",
            new_password: "Jecha Icciitii Haaraa",
            confirm_password: "Jecha Icciitii Mirkaniessi",
            update_btn: "Eenyummeessaa Haaromsi",
            updating_btn: "Haaromsaa jira..."
        },
        system_status: {
            page_title: "Pirootokoolii Sirnaa",
            header: "Argama Sirnaa",
            title: "To’annoo Seensaa",
            subtitle: "Argama waliigalaa portaalii ACAGMS bulchi.",
            mode: "Haala",
            active: "Hojirra jira",
            maintenance: "Suphaarra jira",
            inactive: "Hojii hin jiru",
            save_btn: "Jijjiirama Pirootokoolii Olkaa'i",
            updating_btn: "Haaromsaa jira..."
        },
        profile: {
            title: 'Eenyummeessaa Miiltoo',
            subtitle: 'Odeeffannoo dhuunfaa galmaa’ee fi teessoo quunnamtii keessan ilaalaa.',
            read_only: 'Dubbisa Qofa',
            verified_notice: 'Odeeffannoon eenyummeessaa keessanii yeroo galmee mirkanaa’eera. Odeeffannoo kana haroomsuuf, maaloo waajjira Bulchiinsa Magaalaa Adaamaa daawwadhaa ykn deeggarsa gaafadhaa.',
            first_name: 'Maqaa',
            last_name: 'Maqaa Abbaa',
            email: 'Teessoo Imeeyilii',
            phone: 'Lakkoofsa Bilbilaa',
            security_footer: 'Odeeffannoon keessan pirotokoolii nageenyaa ACAGMS tiin eegamaadha.'
        },
        settings: {
    title: "Sajataa",
    security: "Nageenya",
    settings: "Sajataa",
    subtitle: "Ragaa seensaa kee bulchi",
    update_password: "Iggitaa Haaromsi",
    password_desc: "Herrega kee nageenya qabu gochuuf iggitaa cimaa fayyadami.",
    current_password: "Iggitaa Ammee",
    new_password: "Iggitaa Haaraa",
    confirm_password: "Iggitaa Mirkaneessi",
    save: "Olkaa'i",
    saved: "Olkaa'ameera",
    processing: "Hojjetamaa jira..."
},
        
       visitor_dashboard: {
    "nav_title": "Daashboordii",
    "welcome_back": "Baga Deebitee Dufte",
    "hello": "Akkam",
    "explore_desc": "Filannoowwan miiressa keetii sakatta'i akkasumas miiressa kee bulchi!",
    "btn_book": "Miiressa Haaraa",
    "btn_history": "Seenaa Miiressaa",
    "pending_bookings": "Miiressa Eeggamaa Jira",
    "approved_bookings": "Miiressa Mirkanaa'e",
    "recent_bookings": "Miiressawwan Dhiyoo",
    "view_all": "Hunda Agarsiisi",
    "table_hall": "Galma",
    "table_date": "Guyyaa",
    "table_status": "Haala",
    "table_notes": "Yaada",
    "no_bookings_found": "Miiressi argame hin jiru",
    "no_bookings_desc": "Hanga ammaatti iddoo agarsiisa galmaatiif miiressa miiressitanii hin beektan.",
    "create_booking": "Miiressa Uumi"
  },
        visitor_booking: {
    title: 'Miseensa Haaraa Ajajuu',
    
    // Steps
    step_select_hall: 'Galma Filadhu',
    step_visitor_type: 'Gosa Daawwataa',
    step_schedule: 'Sagantaa Daawwannaa',
    
    // Headers & Subtitles
    header_choose_halls: 'Giddugala ykn Galma tokkoo fi isaa ol filadhu',
    subtitle_choose_halls: 'Itti fufuuf galma tokko ykn isaa ol filadhu',
    header_visitor_type: 'Gosa Daawwataa Filadhu',
    header_schedule: 'Sagantaa Qabadhu',
    
    // Categories
    category_normal: 'Daawwataa Idilee',
    category_vip: 'Daawwataa Kabajamaa (VIP)',
    
    // Labels
    label_date: 'Guyyaa Filatame',
    label_visitor_count: 'Baay\'ina Daawwattootaa meeqa?',
    label_upload_letter: 'Xalayaa Deggersaa Olfisiisi',
    label_time_slot: 'Yeroo Daawwannaa',
    
    // Slots
    slot_early_morning: 'Ganama Ganama',
    slot_mid_morning: 'Giddugaleessa Ganamaa',
    slot_late_morning: 'Aadaa Ganamaa',
    slot_early_afternoon: 'Waree Dura',
    slot_mid_afternoon: 'Waree Booda Giddugaleessa',
    slot_late_afternoon: 'Waree Booda Waaree',
    
    // Buttons
    btn_continue: 'Itti fufi',
    btn_back_halls: 'Gara Galmaatti Deebi\'i',
    btn_back: 'Duubatti',
    btn_confirm: 'Mirkaneessi',
    btn_processing: 'Adeemsisamaa jira...',
    
    // Alerts & Alerts texts
    alert_restricted_title: 'Iddoon Kun Daangeffameera',
    alert_select_hall_title: 'Galma Filadhu',
    alert_select_hall_text: 'Maaloo yoo xiqqaate galma tokko filadhu',
    alert_weekend_title: 'Dhuma Torbeetti Hin Heyyamamu',
    alert_weekend_text: 'Guyyoota Wiixata-Jimaataa qofatti qabachuun danda\'ama',
    alert_missing_doc_title: 'Xalayaan Hin Jiru',
    alert_missing_doc_text: 'Miseensa VIP tiif xalayaan mootummaa ni barbaadama',
    alert_select_slot_title: 'Yeroo Filadhu',
    alert_select_slot_text: 'Maaloo yeroo tokko osoo hin mirkaneessin dura filadhu',
    alert_success_text: 'Daawwannaan keessan milkiidhaan qabameera!',
    alert_failed_title: 'Gaaffiin Hin Milkoofne',
    alert_failed_text: 'Maaloo odeeffannoo galfame deebisaa mirkaneessaa'
},
        login: {
            title: "Seenau",
            subtitle: "Tajaajila Mootummaa Diijitaalaa",
            welcome: "Baga Nagaan Dhufte",
            description: "Eenyummeessa yoo qabaattan, gara dashboordiitti darbuuf maaloo seenaa",
            email_label: "Teessoo Iimeelii",
            email_placeholder: "Iimeelii keessan galchaa",
            password_label: "Jecha Iccitii",
            brand_city: "BULCHIINSA",
            brand_admin: "MAGAALAA ADAAMAA",
            sidebar_subtitle: "SIRNA BULCHIINSA GALERII",
            forgot_password: "Jecha icchitii dagattee?",
            remember_me: "Na yaadadhu",
            sign_in_btn: "Gara Dashboarditti Seeni",
            authenticating: "Mirkaneessaa jira...",
            no_account: "Eenyummeessa hin qabduu?",
            
            sign_up: "Galmaa'i",
            footer: "© 2026 Bulchiinsa Magaalaa Adaamaa - Inisheetiivii Magaalaa Smartii"
        },
        history: {
            qr_pass: 'QR Pass',
            actions: 'Gochaawwan',
            zoom: 'Guddisi',
            btn_ticket: 'Tikiteetti',
            btn_download: 'PDF buufadhu',
            btn_close: 'Cufi',
            qr_title: 'Waraqaa Seensaa',
            general_access: 'Daawwannaa Idilee',
            empty_feedback: 'Yaanni dhiyaate hin jiru.',
            swal_title: 'Haquu barbaadu?',
            swal_text: 'Iddoo qabachuu kana haquu keessan mirkaneessitanii?',
            swal_confirm: 'Eeyyee, haqui!'
        },
        visitor_notification: {
    "nav_title": "Beeksisoota",
    "title": "Giddugala Beeksisaa",
    "subtitle": "Oduuwwan gamaaggama daawwannaa kaampaasii fi sagantaa naannoo hordofaa.",
    "emergency_title": "Xiyyeeffannoo Barbaada",
    "emergency_desc": "Beeksisoota xiyyeeffannoo barbaadan kan hin dubbifamne {count} qabdu.",
    "clear_all": "Hunda Haqi",
    "mark_read": "Hunda Akka Dubbifametti Mallatteessi",
    "filter_all": "Beeksisa Hunda",
    "filter_unread": "Kan Hin Dubbifamne Qofa",
    "filter_important": "Akeekkachiisa Ariifachiisaa",
    "empty_title": "Hundi Qulqulluudha!",
    "empty_desc": "Yeroo ammaa kanatti beeksisni haaraan argame hin jiru.",
    "confirm_delete": "Beeksisa kana haquu akka barbaaddu mirkaneessitee?",
    "confirm_clear": "Beeksisoota hunda guutummaatti haquu akka barbaaddu mirkaneessitee?",
    "suggested_slot": "Yeroo Sagantaa Yaadame",
    "accept_rebook": "Amma Sagantaa Toffadhu"
  },
        visitor_feedback: {
      "title": "Yaada Ergi",
      "header": "Yaada Keessan Kennaa",
      "lock_title": "Yaada Kennuun Cufameera",
      "lock_text": "Maaloo jalqaba galmawwan daawwadhaa, achis yaada erguu dandeessu.",
      "btn_dashboard": "Gara Daashboordiitti Deebi'i",
      "type_general": "Yaada Waliigalaa",
      "type_hall": "Yaada Galmaa",
      "label_hall": "Galma Filadhu",
      "placeholder_hall": "Galma daawwattan filadhaa",
      "label_subject": "Mata Duree",
      "placeholder_subject": "Mata dureen ijoo yaada keessanii maali?",
      "label_sentiment": "Ramaddii Muuxannoo",
      "opt_satisfaction": "Gammachuu",
      "opt_neutral": "Giddu-galeessa",
      "opt_unsatisfactory": "Kan Hagam Hin Gammachiisne",
      "label_rating": "Sadarkaa Kennuu",
      "label_message": "Ergaa Yaadaa Bal'aa",
      "placeholder_message": "Muuxannoo qulqullina ykn adda ta'an as irratti hiraa...",
      "btn_add_photo": "Suura Dabali",
      "upload_hint": "Ol'aanaan 3MB, JPG/PNG/WEBP",
      "btn_cancel": "Haqi",
      "btn_submit": "Yaada Ergi",
      "sending": "Ergamaa Jira...",
      "error_title": "Dogoggora",
      "error_max_images": "Suurawwan haala ol'aanaan 3 qofa fe'uu dandeessu",
      "error_format": "bifa suuraa kan hin deeggaramnedha.",
      "error_size": "baay'ee guddaadha. Hamma ol'aanaan 3MB dha.",
      "error_gibberish_title": "Ergaa Keessan Irra Deebi'aa Ilaala",
      "error_gibberish_text": "Ergaan keessan jechoota sirrii hin taane fakkaata. Maaloo barreeffama ifa ta'e galchaa.",
      "success_title": "Galatoomaa!",
      "success_text": "Yaadin keessan milkiidhaan ergameera."
    },
    visitor_profile: {
    "title": "Profila Daawwataa",
    "subtitle": "Odeeffannoo kee asitti ilaali.",
    "read_only": "Dubbisuuf qofa",
    "verified_notice": "Odeeffannoon kee mirkanaa'eera.",
    "first_name": "Maqaa",
    "last_name": "Maqaa Abbaa",
    "email": "Iimeelii",
    "phone": "Lakkoofsa Bilbilaa",
    "security_footer": "Sababa nageenyaatiin, odeeffannoon tokko tokko jijjiiramuu hin danda'an."
  },
  visitor_settings: {
    "page_title": "Qajeelfa Nageenyaa",
    "title": "Nageenya",
    "subtitle": "Ijoolee lakkoofsa icciitii kee haaromsuun nageenya kee eeggadhu.",
    "current_password": "Icciitii Ammaa",
    "new_password": "Icciitii Haaraa",
    "confirm_password": "Icciitii Haaraa Mirkaneessi",
    "placeholder_current": "Icciitii amma fayyadamtu galchi",
    "placeholder_new": "Icciitii haaraa galchi",
    "placeholder_confirm": "Icciitii haaraa deebitee galchi",
    "footer_note": "Nageenya keetiif, icciitiin kee dheeraa fi iddoo hin qabne ta'uu isaa mirkaneessi.",
    "btn_update": "Icciitii Haaromsi",
    "btn_processing": "Haaromsaa jira...",
    "success_title": "Milkaa'e!",
    "success_text": "Icciitiin kee haaromfameera."
  },
  


        feedbacks_for_guide: {
            title: "Yaada",
            portal_label: "Portaalii Qajeelfamaa • Gammachuu Daawwattootaa Hordofuu",
            search_placeholder: "Daawwataa ykn yaada barbaadi...",
            received: "Kan fudhatame",
            visitor: "Daawwataa",
            no_feedback: "Yaanni hin argamne kan",
            delete_confirm: "Yaada kana tarree keessan keessaa haquu barbaadu?",
            today: "Har'a"
        },
        guide_scanner: {
            title: "Mirkaneessa Seensaa",
            start_camera: "Kaameraa Jalqabi",
            ready: "Dubbisuuf qophiidha...",
            scanning: "Dubbisamaa jira...",
            access_granted: "Hayyamameera",
            access_denied: "Tiketiin sirrii miti"
        },
        // ... existing keys
        guide_login: {
            title: 'Qajeelfama',
            portal: 'Portal',
            subtitle: 'Seensa Buufata Ofischaalaa',
            hall_label: 'Galma Gaalarii Ramadame',
            hall_placeholder: 'Buufata keessan filadhaa',
            email_label: 'Imeeyilii Hojii',
            password_label: 'Iggitaa Nageenyaa',
            remember: 'Buufata kana yaadadhu',
            btn_access: 'Hayyama Mirkaneessi',
            btn_verifying: 'Mirkaneessaa jira...',
            back_link: 'Gara Karra Guddaatti Deebi’i'
        },
    profile: {
            subtitle: 'Odeeffannoo kee ilaali',
            email: 'Imeeyilii',
            phone: 'Bilbila',
            security_footer: 'Odeeffannoon kee eegamaadha'
        },
         "admin_Gallery": {
        "page_title": "Bulchiinsa Galmee",
        "gallery": "Galmee",
        "studio": "Istuudiyoo",
        "description": "Faayiloota dijitaalaa fi suuraa keessan bulchi.",
        "delete_selection": "Kan Filataman Haqi",
        "admin_mode": "Haala Admin",
        "edit_asset": "Faayilii Sirreessi",
        "add_asset": "Faayilii Haaraa Dabaluu",
        "cancel_edit": "Sirreessuu Dhiisi",
        "drag_images_here": "Suuraalee asitti harkisi",
        "or": "ykn",
        "browse_files": "faayiloota filadhu",
        "from_device": "meeshaa irraa",
        "internal_title": "Mata Duree",
        "entry_name": "Maqaa galchaa...",
        "uploading": "OLKAA'AA JIRA...",
        "update_asset": "FAAYILII HAAROMSI",
        "publish_asset": "FAAYILII MAXXANSI",
        "live_preview": "Dursee Ilaali",
        "awaiting_content": "Qabiyyee Eeggachaa Jira",
        "untitled_asset": "Faayilii Maqaa Hin Qabne",
        "library_catalog": "Kuusaa Galmee",
        "filter_title": "Mata dureen barbaadi...",
        "no_assets": "Faayilli mootummaa hin argamne.",
        "edit": "Sirreessi",
        "delete": "Haqi",
        "enter_title": "Maqaa galchi",
        "asset_updated": "Faayilli haaromfameera ✨",
        "image_published": "Suuraan maxxanfameera 🚀",
        "confirm_delete": "Faayila kana keessaa haquu barbaaddaa?",
        "deleted_success": "Milkaa’inaan haqameera",
        "delete_selected": "Kan filataman haqi",
        "bulk_complete": "Hojiin walitti qabame xumurameera"
         },

        
         guide_feedback: {
            title: "Yaada",
            feedbacks: "Yaada",
            subtitle: "Portal Qajeelfamaa",
            search: "Daawwataa ykn yaada barbaadi...",
            visitor: "Daawwataa",
            received: "Fudhatame",
            today: "Har'a",
            empty: "Hin argamne",
            confirm_delete: "Yaada kana haquu barbaadduu?"
        }
    }
};

// --- i18n Instance ---
const i18n = createI18n({
    legacy: false, 
    locale: localStorage.getItem('lang') || 'om',
    fallbackLocale: 'en',
    messages,
});

createInertiaApp({
    title: (title) => (title ? `${title} - ${appName}` : appName),
    resolve: (name) => resolvePageComponent(`./Pages/${name}.vue`, import.meta.glob('./Pages/**/*.vue')),
    setup({ el, App, props, plugin }) {
        const app = createApp({ render: () => h(App, props) });

        app.use(plugin)
           .use(ZiggyVue, window.Ziggy)
           .use(i18n);

        // Make translation function global
        app.config.globalProperties.$t = i18n.global.t;

        // Watch for language changes to update localStorage and document attributes
        watch(
            () => i18n.global.locale.value,
            (val) => {
                localStorage.setItem('lang', val);
                document.documentElement.lang = val;
            },
            { immediate: true }
        );

        return app.mount(el);
    },
    progress: {
        color: '#4B5563',
    },
});