import './bootstrap';
import '../css/app.css';

import { createApp, h, watch } from 'vue';
import { createInertiaApp } from '@inertiajs/vue3';
import { resolvePageComponent } from 'laravel-vite-plugin/inertia-helpers';
import { ZiggyVue } from '../../vendor/tightenco/ziggy'; 
import { createI18n } from 'vue-i18n';

const appName = import.meta.env.VITE_APP_NAME || 'ACAGMS';

// --- Combined & Organized Translation Messages ---
const messages = {
    en: {
        nav1: {
            dashboard: "Dashboard",
            new_booking: "New Booking",
            history: "History",
            notifications: "Notifications",
            feedback: "Feedback",
            profile: "Profile",
            settings: "Settings",
            logout: "Logout",
            main: "Main",
            preferences: "Account",
            overview: "Overview",
        },
         
        register: {
      title: "Create Account",
      subtitle: "Fill in the details below",
      first_name: "First Name",
      last_name: "Last Name",
      email: "Email Address",
      phone: "Phone Number",
      visitor_category: "Visitor Category",
      password: "Password",
      confirm_password: "Confirm Password",
      register_btn: "Register",
      processing: "Processing...",
      have_account: "Already have an account?",
      sign_in: "Sign In",
      local: "Local Visitor",
      foreign: "Foreign Visitor",
      welcome_title: "Welcome!",
      welcome_text: "Your account has been created successfully.",
      open_dashboard: "Open Dashboard",
      validation_failed: "Validation Failed",
      check_form: "Please check your form inputs"
    },
            admin: {
    "dashboard": "Admin Panel",
    "bookings": "All Bookings",
    "halls": "Hall Assets",
    "announcements": "Broadcasts",
    "reports": "Data Reports",
    "guides": "Staff Guides",
    "feedback": "User Feedback",
    "gallery": "Gallery Admin",
    "profile": "Admin Settings",
    "security": "System Security",
    "system_health": "System Health",
    "logout": "Exit System"
  },
            admin_dashboard: {
            dashboard: "Dashboard",
            overview: "Overview",
            system_health: "System Health & Real-time Statistics",
            protocol_optimal: "Protocol: Optimal",
            total_visitors: "Total Visitors",
            action_required: "Action Required",
            active_guides: "Active Guides",
            command_center: "Command Center",
            welcome_text: "Welcome to the ACAGMS administrative hub. Manage requests and audit performance protocols.",
            execute_audit: "Execute Audit",
            uptime: "Uptime",
            load: "Load",
            system_logs: "System Logs",
            view_all_logs: "View All Logs"
        },
        
  "action": {
    "update_confirm": "Yes, Update",
    "updated": "Updated",
    "success": "Success",
    "error": "Error",
    "deleted": "Deleted",
    "delete": "Delete",
    "search_placeholder": "Search...",
    "no_records": "No records found.",
    "cancel": "Cancel",
    "save_changes": "Save Changes",
    "confirm_entry": "Confirm Entry"
  },
  "bookings": {
    "info_heading": "Bookings Information",
    "sub_heading": "Visitor Management",
    "create_entry": "Create Entry",
    "status_change_title": "Change Status?",
    "status_change_text": "Update booking #{id} to {status}?"
  },
  "status": {
    "pending": "Pending",
    "approved": "Approved",
    "confirmed": "Confirmed",
    "rejected": "Rejected",
    "cancelled": "Cancelled",
    "extended": "Extended",
    "completed": "Completed"
  },
  "gallery": {
        "title": "City Gallery",
        "back_home": "Back to Home",
        "header_main": "Visual",
        "header_sub": "Archive",
        "description": "A curated collection of Adama's heritage and progress.",
        "view_image": "View Image"
    },

        halls: {
            title: "Gallery Halls",
            subtitle: "Manage physical gallery locations and exhibition spaces",
            total: "Total Halls",
            add_new: "Add New Hall",
            edit_hall: "Edit Hall",
            name_label: "Hall Name",
            name_placeholder: "e.g. Adama History Hall",
            location_label: "Physical Location",
            location_placeholder: "e.g. Floor 1, Block B",
            desc_label: "Description",
            desc_placeholder: "Describe the purpose of this hall...",
            save: "Save Hall",
            update: "Update Hall",
            cancel: "Cancel",
            table_details: "Hall Details",
            table_location: "Location",
            table_actions: "Actions",
            delete_confirm: "Are you sure you want to delete this hall?",
            empty_title: "No halls found",
            empty_desc: "Get started by creating your first gallery hall."
        },
        
    admin_announcement: {
        "page_title": "Enterprise Alert System",
        "control_center": "Admin Control Center",
        "broadcast_title": "Emergency Broadcast",
        "broadcast_subtitle": "Notify all registered visitors immediately.",
        "target_date": "Target Date",
        "reschedule_date": "Reschedule Date",
        "optional": "(Opt)",
        "alert_title": "Alert Title",
        "alert_placeholder": "e.g., Maintenance Closure",
        "message_content": "Message Content",
        "message_placeholder": "Enter the announcement details...",
        "broadcasting": "Broadcasting...",
        "dispatch": "Dispatch Alert",
        "preview": "Live Preview",
        "preview_default_title": "Notification Title",
        "preview_default_msg": "Preview of how users will see this alert...",
        "auto_expire": "Auto-expires after date",
        "smart_tool": "Smart Tool",
        "smart_tool_desc": "Using a Reschedule Date allows the system to automatically suggest new slots to affected visitors.",
        "success": "Broadcast sent successfully!"
    },
    reports: {
    "page_title": "Analytics",
    "dashboard_heading": "Analytics Dashboard",
    "export_print": "Export / Print",
    "weekly_bookings": "Weekly Bookings",
    "monthly_bookings": "Monthly Bookings",
    "quarterly_bookings": "Quarterly Bookings",
    "yearly_bookings": "Yearly Bookings",
    "feedback_good": "Good Feedback",
    "feedback_neutral": "Neutral Feedback",
    "feedback_bad": "Bad Feedback",
    "filter_type_label": "Report Type",
    "filter_period_label": "Time Period",
    "visual_style_label": "Visualization Style",
    "option_all_bookings": "All Bookings",
    "period_all": "All Time",
    "period_weekly": "Last 7 Days",
    "period_monthly": "This Month",
    "period_yearly": "This Year",
    "style_bar": "Bar",
    "style_line": "Line",
    "style_pie": "Pie",
    "style_doughnut": "Doughnut",
    "updating": "Updating...",
    "update_view": "Update View",
    "no_data": "No Data Available",
    "chart_legend_count": "Count",
    "overview_suffix": "Report Overview",
    "status_all": "All Bookings",
    "status_GoodFeedback": "Good Feedback",
    "status_Neutral": "Neutral Feedback",
    "status_BadFeedback": "Bad Feedback"
  },
  guides: {
            title: "Guides Center",
            subtitle: "System-wide personnel management",
            bulkImport: "Bulk Import",
            uploading: "Uploading...",
            total: "Total Personnel",
            assigned: "Assigned",
            unassigned: "Unassigned",
            register: "Register Guide",
            update: "Update Guide",
            fields: {
                name: "Full Name",
                email: "Email Address",
                phone: "Phone",
                gender: "Gender",
                hall: "Assigned Hall"
            },
            buttons: {
                save: "Save Changes",
                confirm: "Confirm Registration"
            },
            search: "Search by name or email...",
            male: "Male",
            female: "Female",
            select: "Select"
        },
        admin_profile: {
            title: "Profile Management",
            avatar_title: "Avatar Management",
            avatar_help: "Upload a square image for best results.",
            change_photo: "Change Photo",
            first_name: "First Name",
            last_name: "Last Name",
            phone: "Phone Number",
            email: "Primary Email",
            save: "Save Changes",
            updating: "Updating..."
        },
        admin_settings: {
            title: "Security Settings",
            subtitle: "Rotate administrative access credentials",
            current_password: "Current Password",
            new_password: "New Password",
            confirm_password: "Confirm Password",
            update_btn: "Update Access Credentials",
            updating_btn: "Updating..."
        },
        system_status: {
            page_title: "System Protocol",
            header: "System Availability",
            title: "Access Control",
            subtitle: "Manage the global availability of the ACAGMS portal.",
            mode: "Mode",
            active: "Active",
            maintenance: "Maintenance",
            inactive: "Inactive",
            save_btn: "Save Protocol Changes",
            updating_btn: "Updating..."
        },
  
        // ... add the rest of your en keys here
         
        profile: {
            title: 'Account Profile',
            subtitle: 'View your registered personal information and contact details.',
            read_only: 'Read Only',
            verified_notice: 'Your profile information was verified during registration. To update these details, please visit the Adama City Administration office or contact support.',
            first_name: 'First Name',
            last_name: 'Last Name',
            email: 'Email Address',
            phone: 'Phone Number',
            security_footer: 'Your information is protected by ACAGMS security protocols.'
        },
        security: {
            title: "Account Security",
            subtitle: "Manage your credentials and protect your account.",
            page_title: "Security Settings",
            current_password: "Current Password",
            new_password: "New Password",
            confirm_password: "Confirm Password",
            placeholder_current: "Enter current password",
            placeholder_new: "Min. 8 characters",
            placeholder_confirm: "Repeat new password",
            footer_note: "Your information is protected by ACAGMS security protocols.",
            btn_update: "Update Password",
            btn_processing: "Processing...",
            success_title: "Security Updated",
            success_text: "Your password has been successfully changed."
        },
        feedbacks: {
            title: 'Visitor Feedbacks',
            total_bookings: 'Total Bookings',
            good: 'Good Feedback',
            neutral: 'Neutral Feedback',
            bad: 'Bad Feedback',
            visitor: 'Visitor',
            review_mgmt: 'Review Management',
            submissions: 'Submissions',
            search_placeholder: 'Search by name or message...',
            all_ratings: 'All Ratings',
            stars: 'Stars',
            unknown_user: 'Unknown User',
            no_email: 'No email',
            delete_confirm: 'Are you sure you want to delete this feedback?',
            submitted: 'Submitted',
            no_found: 'No feedbacks found'
        },
        dashboard: {
            welcome_back: 'Welcome Back',
            hello: 'Hello',
            hero_text: 'Explore the beauty of Adama. Secure your spot in our galleries and manage your bookings effortlessly.',
            btn_book: 'Book Visit',
            btn_history: 'View History',
            stat_pending: 'Pending',
            stat_completed: 'Completed',
            stat_overall: 'Overall',
            recent_bookings: 'Recent Bookings',
            view_all: 'All History',
            table_hall: 'Hall / Gallery',
            table_date: 'Visit Date',
            table_status: 'Status',
            table_notes: 'Notes',
            no_notes: 'No notes yet.',
            empty_title: 'No bookings found',
            empty_subtitle: "Start exploring the city's history today.",
            btn_create: 'Create Booking'
        },
        bookings: {
            create_title: 'Select Galleries',
            create_subtitle: 'Pick one or more destinations for your visit.',
            identify_title: 'Identify Your Visit',
            schedule_title: 'Schedule Your Visit',
            label_hall: 'Select Gallery Hall',
            label_date: 'Visit Date',
            label_visitors: 'Number of Visitors',
            label_slot: 'Preferred Time Slot',
            label_notes: 'Additional Notes (Optional)',
            placeholder_hall: 'Choose a hall',
            placeholder_notes: 'Any special requests...',
            public_visitor: 'Public Visitor',
            public_desc: 'Local residents, students, or tourists.',
            vip_visitor: 'VIP / Official',
            vip_desc: 'Government delegates or researchers.',
            btn_submit: 'Confirm Booking',
            btn_continue: 'Continue to Profile',
            btn_back: 'Back',
            btn_cancel: 'Cancel',
            upload_letter: 'Upload request letter (Optional)',
            processing: 'Processing...',
            success_msg: 'Booking Submitted!',
            error_selection: 'Please select at least one gallery.',
            error_msg: 'Failed to create booking. Please check the form.'
        },
        login: {
            title: "Log in",
            subtitle: "Digital Government Services",
            welcome: "Welcome Back",
            description: "If you have an account, please sign in to continue to the dashboard",
            email_label: "Email Address",
            email_placeholder: "Enter your email",
            brand_city: "ADAMA CITY",
            brand_admin: "ADMINISTRATION",
            sidebar_subtitle: "GALLERY MANAGEMENT SYSTEM",
            password_label: "Password",
            forgot_password: "Forgot password?",
            remember_me: "Remember me",
            sign_in_btn: "Sign In to Dashboard",
            authenticating: "Authenticating...",
            no_account: "Don't have an account?",
            sign_up: "Sign up",
            footer: "© 2026 Adama City Administration - Smart City Initiative"
        },
        history: {
            qr_pass: 'QR Pass',
            actions: 'Actions',
            zoom: 'Zoom',
            btn_ticket: 'Ticket',
            btn_download: 'Download PDF',
            btn_close: 'Close',
            qr_title: 'Your Entry Pass',
            general_access: 'General Access',
            empty_feedback: 'No feedback submitted yet.',
            swal_title: 'Cancel Booking?',
            swal_text: 'Are you sure you want to remove this pending booking?',
            swal_confirm: 'Yes, cancel it!'
        },
        notifications: {
            title: 'Alert Center',
            subtitle: 'Manage your priority updates and schedule changes',
            emergency_title: 'Emergency Notice',
            emergency_desc: 'Notice: You have {count} urgent updates regarding gallery schedules. Please review the flagged notifications below.',
            clear_all: 'Clear All',
            mark_read: 'Mark all as read',
            filter_all: 'All Notifications',
            filter_unread: 'Unread',
            filter_important: 'Important Only',
            empty_title: 'All caught up!',
            empty_desc: 'No notifications found for this category.',
            suggested_slot: 'Suggested New Slot',
            accept_rebook: 'Accept & Re-book',
            confirm_delete: 'Remove this notification?',
            confirm_clear: 'Clear all notifications?'
        },
        feedback: {
            title: 'Send Feedback',
            header: 'Visitor Feedback',
            type_general: 'General',
            type_hall: 'Hall Specific',
            label_hall: 'Select Hall',
            placeholder_hall: 'Choose a location...',
            label_subject: 'Subject',
            placeholder_subject: 'What is this about?',
            label_rating: 'Rate your experience',
            label_message: 'Your Message',
            placeholder_message: 'Tell us more about your visit...',
            btn_add_photo: 'Add Photo',
            btn_cancel: 'Cancel',
            btn_submit: 'Submit Feedback',
            sending: 'Sending...',
            error_gibberish_title: 'Unreadable Message',
            error_gibberish_text: 'Please write your feedback using clear words and spaces.',
            success_title: 'Success!',
            success_text: 'Thank you! Your feedback has been sent to the administration.',
        },
        
    
        // ... existing keys
        guide_login: {
            title: 'Guide',
            portal: 'Portal',
            subtitle: 'Official Station Access',
            hall_label: 'Assigned Gallery Hall',
            hall_placeholder: 'Select your station',
            email_label: 'Professional Email',
            password_label: 'Security Key',
            remember: 'Remember this station',
            btn_access: 'Authorize Access',
            btn_verifying: 'Verifying...',
            back_link: 'Return to Main Gateway'
        },
        nav: {
            overview: 'Overview',
            account: 'Account',
            station: 'Station',
            logout: 'Logout',
        },
        guide_nav: {
            management: 'Guide Management',
            bookings: 'Bookings',
            scanner: 'QR Scanner',
            feedbacks: 'Feedbacks',
            profile: 'Profile',
            security: 'Security',
            no_hall: 'No hall assigned',
        },
        feedbacks_for_guide: {
            title: "Feedbacks",
            portal_label: "Guide Portal • Monitoring Visitor Satisfaction",
            search_placeholder: "Search visitor or comment...",
            received: "Received",
            visitor: "Visitor",
            no_feedback: "No feedback found for",
            delete_confirm: "Remove this feedback from your list?",
            today: "Today"
        },

        
        guide_dashboard: {
            monitor_portal: 'Monitor Portal',
            open_scanner: 'Open Ticket Scanner',
            total_bookings: 'Total Bookings: Your Hall',
            total_desc: 'Total registrations recorded for this station',
            pending_today: 'Pending Today',
            pending_desc: 'Visitors expected to arrive later today',
            arrived_today: 'Arrived Visitors',
            arrived_desc: 'Successful check-ins for current session',
            live_log: 'Live Visitor Log',
            live_monitoring: 'LIVE MONITORING',
            table_visitor: 'Visitor Info',
            table_type: 'Type',
            table_slot: 'Time Slot',
            table_status: 'Status',
            table_actions: 'Actions',
            mark_arrived: 'Mark Arrived',
            mark_noshow: 'Mark No-Show',
            empty_log: 'No visitors found for this hall.',
            confirm_status: 'Mark this visitor as {status}?'
        },
        profile: {
            title: 'Account Profile',
            subtitle: 'View your registered personal information and contact details.',
            email: 'Email Address',
            phone: 'Phone Number',
            security_footer: 'Your information is protected by ACAGMS security protocols.'
        },
        settings: {
    title: "Settings",
    security: "Security",
    settings: "Settings",
    subtitle: "Manage your access credentials",
    update_password: "Update Password",
    password_desc: "Ensure your account is secure with a strong password.",
    current_password: "Current Password",
    new_password: "New Password",
    confirm_password: "Confirm Password",
    save: "Save Changes",
    saved: "Saved",
    processing: "Processing..."
},
guide_scanner: {
            title: "Entry Verification",
            start_camera: "Start Camera",
            ready: "Ready to scan...",
            scanning: "Scanning in progress...",
            access_granted: "Access Granted",
            access_denied: "Invalid Ticket"
        },
        guide_feedback: {
            title: "Feedbacks",
            feedbacks: "Feedbacks",
            subtitle: "Guide Portal • Monitoring Visitor Satisfaction",
            search: "Search visitor or comment...",
            visitor: "Visitor",
            received: "Received",
            today: "Today",
            empty: "No feedback found for",
            confirm_delete: "Remove this feedback from your list?"
        }
    },
    am: {
        nav1: {
            dashboard: "ዳሽቦርድ",
            new_booking: "አዲስ ማስያዣ",
            history: "ታሪክ",
            notifications: "ማሳወቂያ",
            feedback: "አስተያየት",
            profile: "መገለጫ",
            settings: "ቅንብር",
            logout: "ውጣ",
            main: "ዋና",
            preferences: "መለያ",
            overview: "አጠቃላይ",
        },
        register: {
      title: "መለያ ፍጠር",
      subtitle: "ከታች ያሉትን መረጃዎች ይሙሉ",
      first_name: "ስም",
      last_name: "የአባት ስም",
      email: "ኢሜይል",
      phone: "ስልክ ቁጥር",
      visitor_category: "የጎብኚ ክፍል",
      password: "የይለፍ ቃል",
      confirm_password: "ያረጋግጡ",
      register_btn: "ተመዝግብ",
      processing: "በመስራት ላይ...",
      have_account: "አካውንት አለዎት?",
      sign_in: "ግባ",
      local: "አካባቢ ጎብኚ",
      foreign: "ውጭ ጎብኚ",
      welcome_title: "እንኳን ደህና መጡ!",
      welcome_text: "መለያዎ ተፈጥሯል",
      open_dashboard: "ዳሽቦርድ ክፈት",
      validation_failed: "ስህተት",
      check_form: "ፎርሙን ያረጋግጡ"
    },
            admin: {
    "dashboard": "የአስተዳዳሪ ፓነል",
    "bookings": "ሁሉንም ማስያዣዎች",
    "halls": "የአዳራሽ ንብረቶች",
    "announcements": "ማስታወቂያዎች",
    "reports": "ሪፖርቶች",
    "guides": "የመመሪያ ሰራተኞች",
    "feedback": "ግብረመልስ",
    "gallery": "የፎቶ ማስተዳደሪያ",
    "profile": "የአስተዳዳሪ መገለጫ",
    "security": "የስርዓት ደህንነት",
    "system_health": "የስርዓት ሁኔታ",
    "logout": "ከስርዓት ውጣ"
  },
            admin_dashboard: {
            dashboard: "ዳሽቦርድ",
            overview: "አጠቃላይ",
            system_health: "የስርዓት ጤና እና የእውነተኛ ጊዜ ስታቲስቲክስ",
            protocol_optimal: "ፕሮቶኮል፡ በጥሩ ሁኔታ ላይ",
            total_visitors: "ጠቅላላ ጎብኝዎች",
            action_required: "እርምጃ ያስፈልጋል",
            active_guides: "ንቁ መመሪያዎች",
            command_center: "የትዕዛዝ ማዕከል",
            welcome_text: "እንኳን ወደ ACAGMS አስተዳደር ማዕከል በደህና መጡ። ጥያቄዎችን ያስተዳድሩ እና አፈጻጸምን ይገምግሙ።",
            execute_audit: "ኦዲት ያከናውኑ",
            uptime: "የስራ ጊዜ",
            load: "መጫን",
            system_logs: "የስርዓት ምዝግብ ማስታወሻዎች",
            view_all_logs: "ሁሉንም ምዝግብ ማስታወሻዎች ይመልከቱ"
        },
        
  "action": {
    "update_confirm": "አዎ፣ አድስ",
    "updated": "ተሻሽሏል",
    "success": "ተሳክቷል",
    "error": "ስህተት",
    "deleted": "ተሰርዟል",
    "delete": "ሰርዝ",
    "search_placeholder": "ፈልግ...",
    "no_records": "ምንም መረጃ አልተገኘም።",
    "cancel": "ተመለስ",
    "save_changes": "ለውጦችን መዝግብ",
    "confirm_entry": "መረጃውን አረጋግጥ"
  },
  "bookings": {
    "info_heading": "የቦታ ማስያዣ መረጃ",
    "sub_heading": "የጎብኚዎች አስተዳደር",
    "create_entry": "አዲስ መዝግብ",
    "status_change_title": "ሁኔታውን ይለውጡ?",
    "status_change_text": "የማስያዣ ቁጥር {id} ወደ {status} ይለወጥ?"
  },
  "status": {
    "pending": "በጥበቃ ላይ",
    "approved": "የተፈቀደ",
    "confirmed": "የተረጋገጠ",
    "rejected": "የተነገረ",
    "cancelled": "የተሰረዘ",
    "extended": "የተራዘመ",
    "completed": "ተጠናቋል"
  },
  "gallery": {
        "title": "የከተማው ጋለሪ",
        "back_home": "ወደ መነሻ ተመለስ",
        "header_main": "የምስል",
        "header_sub": "መዝገብ",
        "description": "የአዳማን ቅርሶች እና እድገቶች የሚያሳይ ስብስብ።",
        "view_image": "ምስሉን ይመልከቱ"
    },
        halls: {
            title: "የጋለሪ አዳራሾች",
            subtitle: "የጋለሪ ቦታዎችን እና የኤግዚቢሽን ክፍሎችን ያስተዳድሩ",
            total: "ጠቅላላ አዳራሾች",
            add_new: "አዲስ አዳራሽ ጨምር",
            edit_hall: "አዳራሽ አሻሽል",
            name_label: "የአዳራሹ ስም",
            name_placeholder: "ምሳሌ፡ የአዳማ ታሪክ አዳራሽ",
            location_label: "ትክክለኛ ቦታ",
            location_placeholder: "ምሳሌ፡ 1ኛ ፎቅ፣ ብሎክ B",
            desc_label: "መግለጫ",
            desc_placeholder: "ስለ አዳራሹ ዝርዝር መረጃ ይጻፉ...",
            save: "አዳራሹን መዝግብ",
            update: "መረጃውን አዘምን",
            cancel: "ተመለስ",
            table_details: "ዝርዝር መረጃ",
            table_location: "ቦታ",
            table_actions: "ድርጊቶች",
            delete_confirm: "ይህንን አዳራሽ ለመሰረዝ እርግጠኛ ነዎት?",
            empty_title: "ምንም አዳራሽ አልተገኘም",
            empty_desc: "የመጀመሪያውን አዳራሽ በመፍጠር ይጀምሩ።"
        },  
        
    admin_announcement: {
        "page_title": "የድርጅት ማስጠንቀቂያ ስርዓት",
        "control_center": "የአስተዳዳሪ መቆጣጠሪያ ማዕከል",
        "broadcast_title": "የአደጋ ጊዜ ስርጭት",
        "broadcast_subtitle": "ሁሉንም የተመዘገቡ ጎብኝዎችን ወዲያውኑ ያሳውቁ።",
        "target_date": "የታለመው ቀን",
        "reschedule_date": "የተቀየረበት ቀን",
        "optional": "(አማራጭ)",
        "alert_title": "የማስጠንቀቂያው ርዕስ",
        "alert_placeholder": "ለምሳሌ፦ የጥገና ዝግ መረጃ",
        "message_content": "የመልዕክቱ ይዘት",
        "message_placeholder": "የማስታወቂያውን ዝርዝሮች ያስገቡ...",
        "broadcasting": "በማስተላለፍ ላይ...",
        "dispatch": "ማስጠንቀቂያውን ላክ",
        "preview": "ቀድሞ እይታ",
        "preview_default_title": "የማስታወቂያ ርዕስ",
        "preview_default_msg": "ተጠቃሚዎች ይህንን ማስጠንቀቂያ እንዴት እንደሚያዩት ቅድመ እይታ...",
        "auto_expire": "ከቀኑ በኋላ በራሱ ጊዜ ያልፋል",
        "smart_tool": "ብልህ መሣሪያ",
        "smart_tool_desc": "የቀጠሮ መቀየሪያ ቀን መጠቀም ስርዓቱ ለተጎዱ ጎብኝዎች አዲስ ጊዜ እንዲጠቁም ያስችለዋል።",
        "success": "መልዕክቱ በተሳካ ሁኔታ ተላልፏል!"
    },
    reports: {
    "page_title": "ትንታኔዎች",
    "dashboard_heading": "የትንታኔ ዳሽቦርድ",
    "export_print": "አውርድ / አትም",
    "weekly_bookings": "ሳምንታዊ ምዝገባዎች",
    "monthly_bookings": "ወርሃዊ ምዝገባዎች",
    "quarterly_bookings": "የሩብ ዓመት ምዝገባዎች",
    "yearly_bookings": "ዓመታዊ ምዝገባዎች",
    "feedback_good": "ጥሩ አስተያየት",
    "feedback_neutral": "መካከለኛ አስተያየት",
    "feedback_bad": "መጥፎ አስተያየት",
    "filter_type_label": "የሪፖርት ዓይነት",
    "filter_period_label": "የጊዜ ገደብ",
    "visual_style_label": "የአቀራረብ ዘይቤ",
    "option_all_bookings": "ሁሉም ምዝገባዎች",
    "period_all": "ሁልጊዜ",
    "period_weekly": "ያለፉት 7 ቀናት",
    "period_monthly": "በዚህ ወር",
    "period_yearly": "በዚህ ዓመት",
    "style_bar": "ባር",
    "style_line": "መስመር",
    "style_pie": "ፓይ",
    "style_doughnut": "ዶናት",
    "updating": "በማዘመን ላይ...",
    "update_view": "እይታውን አዘምን",
    "no_data": "ምንም መረጃ የለም",
    "chart_legend_count": "ብዛት",
    "overview_suffix": "ሪፖርት አጠቃላይ እይታ",
    "status_all": "ሁሉም ምዝገባዎች",
    "status_GoodFeedback": "ጥሩ አስተያየት",
    "status_Neutral": "መካከለኛ አስተያየት",
    "status_BadFeedback": "መጥፎ አስተያየት"
  },
  guides: {
            title: "የመመሪያ ማዕከል",
            subtitle: "የሰራተኞች አስተዳደር እና ምደባ",
            bulkImport: "በጅምላ አስገባ",
            uploading: "በመጫን ላይ...",
            total: "ጠቅላላ ሰራተኞች",
            assigned: "የተመደቡ",
            unassigned: "ያልተመደቡ",
            register: "መመሪያ ይመዝግቡ",
            update: "መመሪያ ያድሱ",
            fields: {
                name: "ሙሉ ስም",
                email: "ኢሜል",
                phone: "ስልክ",
                gender: "ጾታ",
                hall: "የተመደበበት አዳራሽ"
            },
            buttons: {
                save: "ለውጦችን አስቀምጥ",
                confirm: "ምዝገባውን አረጋግጥ"
            },
            search: "በስም ወይም በኢሜል ፈልግ...",
            male: "ወንድ",
            female: "ሴት",
            select: "ይምረጡ"
        },
        feedbacks: {
            title: 'የጎብኝዎች አስተያየት',
            total_bookings: 'ጠቅላላ ምዝገባዎች',
            good: 'ጥሩ አስተያየት',
            neutral: 'መካከለኛ አስተያየት',
            bad: 'መጥፎ አስተያየት',
            visitor: 'ጎብኝ',
            review_mgmt: 'የአስተያየት አስተዳደር',
            submissions: 'የገቡ አስተያየቶች',
            search_placeholder: 'በስም ወይም በመልእክት ፈልግ...',
            all_ratings: 'ሁሉም ደረጃዎች',
            stars: 'ኮከቦች',
            unknown_user: 'ያልታወቀ ተጠቃሚ',
            no_email: 'ኢሜይል የለም',
            delete_confirm: 'ይህንን አስተያየት ለማጥፋት እርግጠኛ ነዎት?',
            submitted: 'ገብቷል',
            no_found: 'ምንም አስተያየት አልተገኘም'
        },
        admin_profile: {
            title: "የፕሮፋይል አስተዳደር",
            avatar_title: "የአቫታር አስተዳደር",
            avatar_help: "ለተሻለ ውጤት ካሬ ምስል ይስቀሉ::",
            change_photo: "ፎቶ ቀይር",
            first_name: "ስም",
            last_name: "የአባት ስም",
            phone: "ስልክ ቁጥር",
            email: "ዋና ኢሜይል",
            save: "ለውጦችን አስቀምጥ",
            updating: "በማዘመን ላይ..."
        },
        admin_settings: {
            title: "የደህንነት ቅንብሮች",
            subtitle: "የአስተዳዳሪ መግቢያ ምስጢር ቃል ይቀይሩ",
            current_password: "ያሁኑ ምስጢር ቃል",
            new_password: "አዲስ ምስጢር ቃል",
            confirm_password: "አዲሱን ምስጢር ቃል ያረጋግጡ",
            update_btn: "መረጃውን አዘምን",
            updating_btn: "በማዘመን ላይ..."
        },
        system_status: {
            page_title: "የስርዓት ፕሮቶኮል",
            header: "የስርዓት ተገኝነት",
            title: "የመግቢያ ቁጥጥር",
            subtitle: "የ ACAGMS ፖርታል አጠቃላይ ተገኝነትን እዚህ ያስተዳድሩ::",
            mode: "ሁነታ",
            active: "ንቁ",
            maintenance: "ጥገና ላይ",
            inactive: "አይሰራም",
            save_btn: "ለውጦችን አስቀምጥ",
            updating_btn: "በማዘመን ላይ..."
        },
        


        guide_nav: {
            management: 'የመመሪያ አስተዳደር',
            bookings: 'ቦታ ማስያዣዎች',
            scanner: 'QR ስካነር',
            feedbacks: 'አስተያየቶች',
            profile: 'መገለጫ',
            security: 'ደህንነት',
            no_hall: 'ምንም አዳራሽ አልተመደበም',
            station: 'የአሁኑ ጣቢያ'
        },
        feedbacks_for_guide: {
            title: "አስተያየቶች",
            portal_label: "የመመሪያ ፖርታል • የጎብኝዎችን እርካታ መከታተያ",
            search_placeholder: "ጎብኝ ወይም አስተያየት ፈልግ...",
            received: "የደረሰበት ቀን",
            visitor: "ጎብኝ",
            no_feedback: "ምንም አስተያየት አልተገኘም ለ",
            delete_confirm: "ይህንን አስተያየት ከዝርዝርዎ ውስጥ ያስወግዱት?",
            today: "ዛሬ"
        },
        
        guide_dashboard: {
            monitor_portal: 'የክትትል ፖርታል',
            open_scanner: 'ቲኬት ስካነር ክፈት',
            total_bookings: 'ጠቅላላ ምዝገባ፡ የእርስዎ አዳራሽ',
            total_desc: 'ለዚህ ጣቢያ የተቀዳ ሙሉ የምዝገባ ብዛት',
            pending_today: 'ዛሬ የሚጠበቁ',
            pending_desc: 'ዛሬ በኋላ ይመጣሉ ተብለው የሚጠበቁ ጎብኚዎች',
            arrived_today: 'የገቡ ጎብኚዎች',
            arrived_desc: 'ለአሁኑ ክፍለ ጊዜ በተሳካ ሁኔታ የገቡ',
            live_log: 'የጎብኚዎች መዝገብ',
            live_monitoring: 'ቀጥታ ክትትል',
            table_visitor: 'የጎብኚ መረጃ',
            table_type: 'ዓይነት',
            table_slot: 'የጉብኝት ሰዓት',
            table_status: 'ሁኔታ',
            table_actions: 'ድርጊቶች',
            mark_arrived: 'ገብቷል በል',
            mark_noshow: 'አልመጣም በል',
            empty_log: 'ለዚህ አዳራሽ የተገኘ ጎብኚ የለም።',
            confirm_status: 'ይህን ጎብኚ {status} ብለው ምልክት ማድረግ ይፈልጋሉ?'
        },
        profile: {
            title: 'የመገለጫ መረጃ',
            subtitle: 'የተመዘገቡ የግል መረጃዎችን እና የአድራሻ ዝርዝሮችን ይመልከቱ።',
            read_only: 'ለንባብ ብቻ',
            verified_notice: 'የመገለጫ መረጃዎ በምዝገባ ወቅት ተረጋግጧል። እነዚህን ዝርዝሮች ለማዘመን እባክዎን የአዳማ ከተማ አስተዳደር ቢሮን ይጎብኙ ወይም ድጋፍ ሰጪዎችን ያነጋግሩ።',
            first_name: 'ስም',
            last_name: 'የአባት ስም',
            email: 'ኢሜይል አድራሻ',
            phone: 'ስልክ ቁጥር',
            security_footer: 'መረጃዎ በACAGMS የደህንነት ፕሮቶኮሎች የተጠበቀ ነው።'
        },
        settings: {
    title: "ቅንብሮች",
    security: "ደህንነት",
    settings: "ቅንብሮች",
    subtitle: "የመግቢያ መረጃዎን ያስተዳድሩ",
    update_password: "የይለፍ ቃል አዘምን",
    password_desc: "መለያዎን በጠንካራ የይለፍ ቃል ይጠብቁ።",
    current_password: "የአሁኑ የይለፍ ቃል",
    new_password: "አዲስ የይለፍ ቃል",
    confirm_password: "የይለፍ ቃል አረጋግጥ",
    save: "አስቀምጥ",
    saved: "ተቀምጧል",
    processing: "በመሰራት ላይ..."
},
        security: {
            title: "የመለያ ደህንነት",
            subtitle: "መለያዎን ይጠብቁ እና የይለፍ ቃልዎን ያስተዳድሩ።",
            page_title: "የደህንነት ቅንብሮች",
            current_password: "የአሁኑ የይለፍ ቃል",
            new_password: "አዲስ የይለፍ ቃል",
            confirm_password: "የይለፍ ቃሉን ያረጋግጡ",
            placeholder_current: "የአሁኑን የይለፍ ቃል ያስገቡ",
            placeholder_new: "ቢያንስ 8 ቁምፊዎች",
            placeholder_confirm: "አዲሱን የይለፍ ቃል ይድገሙ",
            footer_note: "መረጃዎ በACAGMS የደህንነት ፕሮቶኮሎች የተጠበቀ ነው።",
            btn_update: "የይለፍ ቃል አዘምን",
            btn_processing: "በመሰራት ላይ...",
            success_title: "ደህንነት ተዘምኗል",
            success_text: "የይለፍ ቃልዎ በተሳካ ሁኔታ ተቀይሯል።"
        },
        dashboard: {
            welcome_back: 'እንኳን ደህና መጡ',
            hello: 'ሰላም',
            hero_text: 'የአዳማን ውበት ይጎብኙ። በጋለሪዎቻችን ውስጥ ቦታ ያስይዙ እና ትዕዛዝዎን በቀላሉ ያስተዳድሩ።',
            btn_book: 'ቦታ ያስይዙ',
            btn_history: 'ታሪክ ይመልከቱ',
            stat_pending: 'በጥበቃ ላይ',
            stat_completed: 'ተጠናቋል',
            stat_overall: 'ጠቅላላ',
            recent_bookings: 'የቅርብ ጊዜ ምዝገባዎች',
            view_all: 'ሙሉ ታሪክ',
            table_hall: 'አዳራሽ / ጋለሪ',
            table_date: 'የጉብኝት ቀን',
            table_status: 'ሁኔታ',
            table_notes: 'ማስታወሻዎች',
            no_notes: 'ምንም ማስታወሻ የለም።',
            empty_title: 'ምንም የተመዘገበ መረጃ የለም',
            empty_subtitle: 'የከተማዋን ታሪክ ዛሬ ማሰስ ይጀምሩ።',
            btn_create: 'አዲስ አስይዝ'
        },
        bookings: {
            create_title: 'አዳራሾችን ይምረጡ',
            create_subtitle: 'ለጉብኝትዎ አንድ ወይም ከዚያ በላይ ቦታዎችን ይምረጡ::',
            identify_title: 'የጉብኝት አይነት',
            schedule_title: 'የጉብኝት ጊዜ ይምረጡ',
            label_hall: 'የጋለሪ አዳራሽ ይምረጡ',
            label_date: 'የጉብኝት ቀን',
            label_visitors: 'የጎብኚዎች ብዛት',
            label_slot: 'የጉብኝት ሰዓት',
            label_notes: 'ተጨማሪ ማስታወሻ (ካለ)',
            placeholder_hall: 'አዳራሽ ይምረጡ',
            placeholder_notes: 'ልዩ ፍላጎት ካለ...',
            public_visitor: 'መደበኛ ጎብኚ',
            public_desc: 'የአካባቢ ነዋሪዎች፣ ተማሪዎች ወይም ቱሪስቶች::',
            vip_visitor: 'ቪአይፒ / ኦፊሴላዊ',
            vip_desc: 'የመንግስት ተወካዮች ወይም ተመራማሪዎች::',
            btn_submit: 'ምዝገባውን አረጋግጥ',
            btn_continue: 'ወደ መገለጫ ቀጥል',
            btn_back: 'ተመለስ',
            btn_cancel: 'ሰርዝ',
            upload_letter: 'የጥያቄ ደብዳቤ ይጫኑ (ካለ)',
            processing: 'በመሰራት ላይ...',
            success_msg: 'ቦታ ማስያዣው ተልኳል!',
            error_selection: 'እባክዎ ቢያንስ አንድ አዳራሽ ይምረጡ::',
            error_msg: 'ምዝገባው አልተሳካም። እባክዎ መረጃውን ያረጋግጡ።'
        },
        login: {
            title: "ይግቡ",
            subtitle: "ዲጂታል የመንግስት አገልግሎቶች",
            welcome: "እንኳን ደህና መጡ",
            description: "መለያ ካለዎት እባክዎ ወደ ዳሽቦርዱ ለመቀጠል ይግቡ",
            email_label: "ኢሜይል አድራሻ",
            brand_city: "የአዳማ ከተማ",
            brand_admin: "አስተዳደር",
            sidebar_subtitle: "የጋለሪ አስተዳደር ስርዓት",
            email_placeholder: "ኢሜይልዎን ያስገቡ",
            password_label: "የይለፍ ቃል",
            forgot_password: "የይለፍ ቃል ረስተዋል?",
            remember_me: "አስታውሰኝ",
            sign_in_btn: "ወደ ዳሽቦርድ ይግቡ",
            authenticating: "በማረጋገጥ ላይ...",
            no_account: "መለያ የለዎትም?",
            sign_up: "ይመዝገቡ",
            footer: "© 2026 የአዳማ ከተማ አስተዳደር - ስማርት ሲቲ ኢኒሼቲቭ"
        },
        history: {
            qr_pass: 'QR ፓስ',
            actions: 'ድርጊቶች',
            zoom: 'አሳድግ',
            btn_ticket: 'ቲኬት',
            btn_download: 'ፒዲኤፍ አውርድ',
            btn_close: 'ዝጋ',
            qr_title: 'የመግቢያ መታወቂያ',
            general_access: 'መደበኛ ጉብኝት',
            empty_feedback: 'ምንም አስተያየት አልተሰጠም።',
            swal_title: 'ቦታ ማስያዣ ይሠረዝ?',
            swal_text: 'ይህን በጥበቃ ላይ ያለ ቦታ ማስያዣ መሰረዝዎን እርግጠኛ ነዎት?',
            swal_confirm: 'አዎ ሰርዝ!'
        },
        notifications: {
            title: 'የማሳወቂያ ማዕከል',
            subtitle: 'ቅድሚያ የሚሰጣቸውን ዝመናዎች እና የጊዜ ሰሌዳ ለውጦችን ያስተዳድሩ',
            emergency_title: 'አስቸኳይ ማሳወቂያ',
            emergency_desc: 'ማሳሰቢያ፡ ከጋለሪ መርሃ ግብሮች ጋር በተያያዘ {count} አስቸኳይ ዝመናዎች አሉዎት። እባክዎ ከታች ያሉትን ምልክት የተደረገባቸውን ማሳወቂያዎች ይመልከቱ።',
            clear_all: 'ሁሉንም አጽዳ',
            mark_read: 'ሁሉንም እንደተነበበ ምልክት አድርግ',
            filter_all: 'ሁሉም ማሳወቂያዎች',
            filter_unread: 'ያልተነበቡ',
            filter_important: 'አስፈላጊ ብቻ',
            empty_title: 'ሁሉም ደርሰዋል!',
            empty_desc: 'ለዚህ ምድብ ምንም ማሳወቂያ አልተገኘም።',
            suggested_slot: 'የቀረበ አዲስ ሰዓት',
            accept_rebook: 'ተቀበል እና እንደገና አስይዝ',
            confirm_delete: 'ይህን ማሳወቂያ ይወገድ?',
            confirm_clear: 'ሁሉንም ማሳወቂያዎች ይኑር?'
        },
        feedback: {
            title: 'አስተያየት ይላኩ',
            header: 'የጎብኚዎች አስተያየት',
            type_general: 'ጠቅላላ',
            type_hall: 'ለአንድ አዳራሽ',
            label_hall: 'አዳራሽ ይምረጡ',
            placeholder_hall: 'ቦታ ይምረጡ...',
            label_subject: 'ርዕስ',
            placeholder_subject: 'ስለ ምንድን ነው?',
            label_rating: 'ደረጃ ይስጡ',
            label_message: 'የእርስዎ አስተያየት',
            placeholder_message: 'ስለ ጉብኝትዎ ተጨማሪ ይንገሩን...',
            btn_add_photo: 'ፎቶ ያክሉ',
            btn_cancel: 'ሰርዝ',
            btn_submit: 'አስተያየት ይላኩ',
            sending: 'በመላክ ላይ...',
            error_gibberish_title: 'የማይነበብ መልዕክት',
            error_gibberish_text: 'እባክዎ ግልጽ ቃላትን እና ክፍተቶችን በመጠቀም አስተያየትዎን ይጻፉ።',
            success_title: 'ተሳክቷል!',
            success_text: 'እናመሰግናለን! አስተያየትዎ ለአስተዳደሩ ተልኳል።',
        },
        // ... existing keys
        guide_login: {
            title: 'የመመሪያ',
            portal: 'ፖርታል',
            subtitle: 'ይፋዊ የጣቢያ መግቢያ',
            hall_label: 'የተመደበው የጋለሪ አዳራሽ',
            hall_placeholder: 'ጣቢያዎን ይምረጡ',
            email_label: 'የስራ ኢሜይል',
            password_label: 'የደህንነት ቁልፍ',
            remember: 'ይህንን ጣቢያ አስታውስ',
            btn_access: 'ፈቃድ አረጋግጥ',
            btn_verifying: 'በማረጋገጥ ላይ...',
            back_link: 'ወደ ዋናው በር ተመለስ'
        },
        nav: {
            overview: 'አጠቃላይ እይታ',
            account: 'መለያ',
            station: 'የአሁኑ ጣቢያ',
            logout: 'ውጣ',
        },
        guide_nav: {
            management: 'የመመሪያ አስተዳደር',
            bookings: 'ቦታ ማስያዣ',
            scanner: 'QR ስካነር',
            feedbacks: 'አስተያየቶች',
            profile: 'መገለጫ',
            security: 'ደህንነት',
            no_hall: 'ምንም አዳራሽ አልተመደበም',
        },
        guide_dashboard: {
            monitor_portal: 'የክትትል ፖርታል',
            open_scanner: 'ቲኬት ስካነር ክፈት',
            total_bookings: 'ጠቅላላ ምዝገባ',
            total_desc: 'ሙሉ የምዝገባ ብዛት',
            pending_today: 'ዛሬ የሚጠበቁ',
            pending_desc: 'ዛሬ በኋላ የሚመጡ',
            arrived_today: 'የገቡ',
            arrived_desc: 'ተሳክቷል',
            live_log: 'የጎብኚ መዝገብ',
            live_monitoring: 'ቀጥታ',
            table_visitor: 'መረጃ',
            table_type: 'ዓይነት',
            table_slot: 'ሰዓት',
            table_status: 'ሁኔታ',
            table_actions: 'እርምጃ',
            mark_arrived: 'ገብቷል',
            mark_noshow: 'አልመጣም',
            empty_log: 'ምንም የለም',
            confirm_status: 'ይህን {status} ብለው ማድረግ?'
        },
        guide_scanner: {
            title: "የመግቢያ ማረጋገጫ",
            start_camera: "ካሜራ አስጀምር",
            ready: "ለመቃኘት ዝግጁ...",
            scanning: "በመቃኘት ላይ...",
            access_granted: "ተፈቅዷል",
            access_denied: "ትኬቱ ትክክል አይደለም"
        },
        profile: {
            subtitle: 'የግል መረጃዎችን ይመልከቱ',
            email: 'ኢሜይል',
            phone: 'ስልክ',
            security_footer: 'መረጃዎ ተጠብቆ ነው'
        },

    
        guide_feedback: {
            title: "አስተያየቶች",
            feedbacks: "አስተያየቶች",
            subtitle: "የመመሪያ ፖርታል",
            search: "ጎብኚ ወይም አስተያየት ፈልግ...",
            visitor: "ጎብኚ",
            received: "ተቀባ",
            today: "ዛሬ",
            empty: "ምንም አልተገኘም",
            confirm_delete: "ይህን አስተያየት ማስወገድ ይፈልጋሉ?"
        }
    },

    or: {
        nav1: {
            dashboard: "Dabsidii",
            new_booking: "Qabannaa Haaraa",
            history: "Seenaa",
            notifications: "Beeksisa",
            feedback: "Yaada",
            profile: "Profile",
            settings: "Sajataa",
            logout: "Ba’i",
            main: "Gara",
            preferences: "Account",
            overview: "Ilaalcha",
        },
        
           admin: {
    "dashboard": "paanaalii Bulchiinsaa",
    "bookings": "Qabannoowwan Hunda",
    "halls": "Qabeenya Galma",
    "announcements": "Beeksisa",
    "reports": "Gabaasa",
    "guides": "Hojjattoota Qajeelchaa",
    "feedback": "Yaada",
    "gallery": "Bulchiinsa Suuraa",
    "profile": "Saagiinsa Bulchiinsaa",
    "security": "Nageenya Sirnaa",
    "system_health": "Fayyaa Sirnaa",
    "logout": "Sirna Keessaa Ba'i"
  },
            admin_dashboard: {
            dashboard: "Daashboordii",
            overview: "Waliigala",
            system_health: "Fayyaa Sirnaa fi Istaatistiiksii Yeroo Real",
            protocol_optimal: "Pirootokoolii: Gaarii",
            total_visitors: "Baay'ina Daawwattootaa",
            action_required: "Tarkaanfii Barbaachisaa",
            active_guides: "Qajeelchitoota Hojirra Jiran",
            command_center: "Wiirtuu Ajajaa",
            welcome_text: "Gara wiirtuu bulchiinsa ACAGMS tti baga nagaan dhuftan. Gaaffiwwan bulchuun akkasumas raawwii odiit godhaa.",
            execute_audit: "Odiitii Raawwadhu",
            uptime: "Yeroo Hojii",
            load: "Loodii",
            system_logs: "Galmee Sirnaa",
            view_all_logs: "Galmeewwan Hunda Ilaali"
        },
    
  "action": {
    "update_confirm": "Eeyyee, Haaromsi",
    "updated": "Haaromeera",
    "success": "Milkaa'eera",
    "error": "Dogoggora",
    "deleted": "Haqumeera",
    "delete": "Haquu",
    "search_placeholder": "Barbaadi...",
    "no_records": "Galmeen hin argamne.",
    "cancel": "Dhiisi",
    "save_changes": "Jijjiirama Galmeessi",
    "confirm_entry": "Galmee Mirkanessi"
  },
  "bookings": {
    "info_heading": "Oodeeffannoo Iddoo Qabachuu",
    "sub_heading": "Bulchiinsa Daawwattootaa",
    "create_entry": "Galmee Haaraa",
    "status_change_title": "Haala jijjiiruu?",
    "status_change_text": "Galmee lakkoofsa {id} gara {status} tti jijjiiruu?"
  },
  "status": {
    "pending": "Eeggachaa jira",
    "approved": "Eeyyamameera",
    "confirmed": "Mirkanaa'eera",
    "rejected": "Kufaa ta'eera",
    "cancelled": "Haqumeera",
    "extended": "Dheerateera",
    "completed": "Xumurameera"
  },
  "gallery": {
        "title": "Gaalarii Magaalaa",
        "back_home": "Gara Manaatti",
        "header_main": "Kuusaa",
        "header_sub": "Fakkii",
        "description": "Hambaalee fi guddina magaalaa Adaamaa kan agarsiisu.",
        "view_image": "Fakkii Ilaali"
    },
  
        halls: {
            title: "Galmawwan Gaalarii",
            subtitle: "Bakka galmawwan gaalarii fi kutaalee agarsiisaa bulchaa",
            total: "Waliigala Galmawwan",
            add_new: "Galma Haaraa Dabali",
            edit_hall: "Galma Haaromsi",
            name_label: "Maqaa Galmaa",
            name_placeholder: "fkn. Galma Seenaa Adaamaa",
            location_label: "Bakka Itti Argamu",
            location_placeholder: "fkn. Floor 1, Block B",
            desc_label: "Ibsa",
            desc_placeholder: "Waa’ee galma kanaa ibsaa...",
            save: "Galma Galmeessi",
            update: "Galma Haaromsi",
            cancel: "Dhiisi",
            table_details: "Odeeffannoo Galmaa",
            table_location: "Bakka",
            table_actions: "Gochaawwan",
            delete_confirm: "Galma kana haquu akka barbaaddu mirkaneeffatteettaa?",
            empty_title: "Galmi argame hin jiru",
            empty_desc: "Galma gaalarii keessan isa jalqabaa uumuun jalqabaa."
        },
        
    admin_announcement: {
        "page_title": "Siri Alartii Intarppiraayizii",
        "control_center": "Giddu-gala To'annoo Admin",
        "broadcast_title": "Tamsaasa Ariifachiisaa",
        "broadcast_subtitle": "Daawwatoota galmaa'an hunda yeroodhumaan beeksisi.",
        "target_date": "Guyyaa Targetii",
        "reschedule_date": "Guyyaa Haqamee",
        "optional": "(Filannoo)",
        "alert_title": "Mata-duree Alartii",
        "alert_placeholder": "fkn, Beeksisa Cufiinsaa Maintenance",
        "message_content": "Qabiyyee Ergaa",
        "message_placeholder": "Bal'ina beeksisaa galchi...",
        "broadcasting": "Tamsaasaa jira...",
        "dispatch": "Alartii Ergi",
        "preview": "Dur-argii",
        "preview_default_title": "Mata-duree Beeksisaa",
        "preview_default_msg": "Akkaataa itti tajaajilamtoonni alartii kana argu danda'an...",
        "auto_expire": "Guyyaa booda ofumaan ni bada",
        "smart_tool": "Meeshaa Smart",
        "smart_tool_desc": "Guyyaa 'Reschedule' fayyadamuun sirni kun daawwattootaaf yeroo haaraa akka gorsu taasisa.",
        "success": "Tamsaasni milkiin ergameera!"
    },
    reports: {
    "page_title": "Xiinxala",
    "dashboard_heading": "Dabaree Xiinxalaa",
    "export_print": "Gadi-buusi / Maxxansi",
    "weekly_bookings": "Galmee Torbee",
    "monthly_bookings": "Galmee Ji'aa",
    "quarterly_bookings": "Galmee Kurmaanaa",
    "yearly_bookings": "Galmee Waggaa",
    "feedback_good": "Yaada Gaarii",
    "feedback_neutral": "Yaada Giddu-galeessaa",
    "feedback_bad": "Yaada Gadhee",
    "filter_type_label": "Gosa Gabaasaa",
    "filter_period_label": "Yeroo",
    "visual_style_label": "Akkaataa Mul'ataa",
    "option_all_bookings": "Galmeewwan Hunda",
    "period_all": "Yeroo Hunda",
    "period_weekly": "Guyyoota 7 Darban",
    "period_monthly": "Ji'a Kana",
    "period_yearly": "Waggaa Kana",
    "style_bar": "Bar",
    "style_line": "Line",
    "style_pie": "Pie",
    "style_doughnut": "Doughnut",
    "updating": "Haaromsaa jira...",
    "update_view": "Mul'ata Haaromsi",
    "no_data": "Oofni hin jiru",
    "chart_legend_count": "Baay'ina",
    "overview_suffix": "Gabaasa Waliigalaa",
    "status_all": "Galmeewwan Hunda",
    "status_GoodFeedback": "Yaada Gaarii",
    "status_Neutral": "Yaada Giddu-galeessaa",
    "status_BadFeedback": "Yaada Gadhee"
  },
  guides: {
            title: "Wiirtuu Qajeelchituu",
            subtitle: "Bulchiinsa fi ramaddii hojjettootaa",
            bulkImport: "Walitti fidi",
            uploading: "Fe'amaa jira...",
            total: "Hojjettoota Waligalaa",
            assigned: "Ramadaman",
            unassigned: "Hin ramadamne",
            register: "Qajeelchituu Galmeessi",
            update: "Qajeelchituu Haaromsi",
            fields: {
                name: "Maqaa Guutuu",
                email: "Teessoo Imeelii",
                phone: "Bilbila",
                gender: "Saala",
                hall: "Galma Ramadame"
            },
            buttons: {
                save: "Jijjiirama Olkaayi",
                confirm: "Galmeessa Mirkaneessi"
            },
            search: "Maqaa ykn imeeliin bari...",
            male: "Dhiira",
            female: "Dhalaa",
            select: "Filadhu"
        },
        feedbacks: {
            title: 'Yaada Daawwattootaa',
            total_bookings: 'Waliigala Qabannaa',
            good: 'Yaada Gaarii',
            neutral: 'Yaada Giddu-galeessa',
            bad: 'Yaada Gadhee',
            visitor: 'Daawwataa',
            review_mgmt: 'Bulchiinsa Yaadaa',
            submissions: 'Yaadota Kennaman',
            search_placeholder: 'Barbaadi...',
            all_ratings: 'Sadarkaa Hunda',
            stars: 'Urjiiwwan',
            unknown_user: 'Nama hin beekamne',
            no_email: 'Imeelii hin qabu',
            delete_confirm: 'Haquu barbaadduu?',
            submitted: 'Kan Ergame',
            no_found: 'Yaanni argame hin jiru'
        },
        
        nav: {
            overview: 'Baafata',
            account: 'Herrega',
            station: 'Buufata',
            logout: 'Ba’i',
        },
        guide_nav: {
            management: 'Bulchiinsa',
            bookings: 'Qabachuu',
            scanner: 'QR Scanner',
            feedbacks: 'Yaada',
            profile: 'Eenyummeessaa',
            security: 'Nageenya',
            no_hall: 'Hin ramadamne',
        },
        guide_dashboard: {
            monitor_portal: 'Portal Hordoffii',
            open_scanner: 'Scanner Tikiteetti Banu',
            total_bookings: 'Waliigala Galmee: Galma Keessan',
            total_desc: 'Baay’ina galmee buufata kanaaf qabame',
            pending_today: 'Har’a kan Eegamu',
            pending_desc: 'Daawwattoota har’a booda dhufan jedhamanii eegaman',
            arrived_today: 'Daawwattoota Dhufan',
            arrived_desc: 'Galmeen milkaa’inaan xumurame',
            live_log: 'Galmee Daawwattootaa',
            live_monitoring: 'HORDOFFII QAAMAA',
            table_visitor: 'Odeeffannoo Daawwataa',
            table_type: 'Gosa',
            table_slot: 'Yeroo',
            table_status: 'Haala',
            table_actions: 'Gochaawwan',
            mark_arrived: 'Dhufeera Jedhi',
            mark_noshow: 'Hin Dhufne Jedhi',
            empty_log: 'Galma kanaaf daawwataan argame hin jiru.',
            confirm_status: 'Daawwataa kana akka {status} tti mallatteessuu barbaadu?'
        },
        admin_profile: {
            title: "Bulchiinsa Piroofayilii",
            avatar_title: "Bulchiinsa Avataaraa",
            avatar_help: "Bu'aa gaariidhaaf fakkii Iskuweerii olkaa'aa.",
            change_photo: "Suuraa Jijjiiri",
            first_name: "Maqaa",
            last_name: "Maqaa Abbaa",
            phone: "Lakk. Bilbilaa",
            email: "Imeelii",
            save: "Jijjiirama Olkaa'i",
            updating: "Haaromsaa jira..."
        },
        admin_settings: {
            title: "Sajeeffama Nageenyaa",
            subtitle: "Jecha icciitii bulchiinsaa jijjiiri",
            current_password: "Jecha Icciitii Ammee",
            new_password: "Jecha Icciitii Haaraa",
            confirm_password: "Jecha Icciitii Mirkaniessi",
            update_btn: "Eenyummeessaa Haaromsi",
            updating_btn: "Haaromsaa jira..."
        },
        system_status: {
            page_title: "Pirootokoolii Sirnaa",
            header: "Argama Sirnaa",
            title: "To’annoo Seensaa",
            subtitle: "Argama waliigalaa portaalii ACAGMS bulchi.",
            mode: "Haala",
            active: "Hojirra jira",
            maintenance: "Suphaarra jira",
            inactive: "Hojii hin jiru",
            save_btn: "Jijjiirama Pirootokoolii Olkaa'i",
            updating_btn: "Haaromsaa jira..."
        },
        profile: {
            title: 'Eenyummeessaa Miiltoo',
            subtitle: 'Odeeffannoo dhuunfaa galmaa’ee fi teessoo quunnamtii keessan ilaalaa.',
            read_only: 'Dubbisa Qofa',
            verified_notice: 'Odeeffannoon eenyummeessaa keessanii yeroo galmee mirkanaa’eera. Odeeffannoo kana haroomsuuf, maaloo waajjira Bulchiinsa Magaalaa Adaamaa daawwadhaa ykn deeggarsa gaafadhaa.',
            first_name: 'Maqaa',
            last_name: 'Maqaa Abbaa',
            email: 'Teessoo Imeeyilii',
            phone: 'Lakkoofsa Bilbilaa',
            security_footer: 'Odeeffannoon keessan pirotokoolii nageenyaa ACAGMS tiin eegamaadha.'
        },
        settings: {
    title: "Sajataa",
    security: "Nageenya",
    settings: "Sajataa",
    subtitle: "Ragaa seensaa kee bulchi",
    update_password: "Iggitaa Haaromsi",
    password_desc: "Herrega kee nageenya qabu gochuuf iggitaa cimaa fayyadami.",
    current_password: "Iggitaa Ammee",
    new_password: "Iggitaa Haaraa",
    confirm_password: "Iggitaa Mirkaneessi",
    save: "Olkaa'i",
    saved: "Olkaa'ameera",
    processing: "Hojjetamaa jira..."
},
        
        dashboard: {
            welcome_back: 'Baga Nagaan Dhuftan',
            hello: 'Akkam',
            hero_text: 'Miidhagina Adaamaa daawwadhaa. Galma keenya keessatti iddoo qabadhaa akkasumas tajaajila keessan salphaatti bulchaa.',
            btn_book: 'Iddoo Qabadhu',
            btn_history: 'Seenaa Ilaali',
            stat_pending: 'Kan Eegamu',
            stat_completed: 'Kan Xumurame',
            stat_overall: 'Waliigala',
            recent_bookings: 'Iddoo Qabachuu Dhiheenya',
            view_all: 'Seenaa Guutuu',
            table_hall: 'Galma / Gaalarii',
            table_date: 'Guyyaa Daawwannaa',
            table_status: 'Haala',
            table_notes: 'Yaada',
            no_notes: 'Yaanni hin jiru.',
            empty_title: 'Iddoo qabachuun hin jiru',
            empty_subtitle: 'Seenaa magaalaa har’a qorachuu jalqabaa.',
            btn_create: 'Haaraa Galchi'
        },
        bookings: {
            create_title: 'Galma Filadhu',
            create_subtitle: 'Daawwannaa keessaniif iddoo tokko ykn isaa ol filadhaa.',
            identify_title: 'Gosa Daawwannaa',
            schedule_title: 'Yeroo Daawwannaa Filadhu',
            label_hall: 'Galma Gaalarii Filadhu',
            label_date: 'Guyyaa Daawwannaa',
            label_visitors: 'Baay’ina Daawwattootaa',
            label_slot: 'Yeroo Filatamaa',
            label_notes: 'Yaada Dabalataa (Yoo jiraate)',
            placeholder_hall: 'Galma filadhu',
            placeholder_notes: 'Gaaffii addaa yoo qabaattan...',
            public_visitor: 'Daawwataa Idilee',
            public_desc: 'Jiraattota naannoo, barattoota ykn tuuristoota.',
            vip_visitor: 'VIP / Ofischaalaa',
            vip_desc: 'Bakka bu’oota mootummaa ykn qorattoota.',
            btn_submit: 'Mirkaneessi',
            btn_continue: 'Gara Eenyummeessatti Itti Fufi',
            btn_back: 'Dequu',
            btn_cancel: 'Haqui',
            upload_letter: 'Xalayaa gaaffii fe’i (Yoo jiraate)',
            processing: 'Hojjetamaa jira...',
            success_msg: 'Galmeeffamuun milkaa’eera!',
            error_selection: 'Maaloo yoo xiqqaate galma tokko filadhaa.',
            error_msg: 'Iddoo qabachuun hin dandahamne. Maaloo foormii keessan deebisaa ilaalaa.'
        },
        login: {
            title: "Seenau",
            subtitle: "Tajaajila Mootummaa Diijitaalaa",
            welcome: "Baga Nagaan Dhufte",
            description: "Eenyummeessa yoo qabaattan, gara dashboordiitti darbuuf maaloo seenaa",
            email_label: "Teessoo Iimeelii",
            email_placeholder: "Iimeelii keessan galchaa",
            password_label: "Jecha Iccitii",
            brand_city: "BULCHIINSA",
            brand_admin: "MAGAALAA ADAAMAA",
            sidebar_subtitle: "SIRNA BULCHIINSA GALERII",
            forgot_password: "Jecha icchitii dagattee?",
            remember_me: "Na yaadadhu",
            sign_in_btn: "Gara Dashboarditti Seeni",
            authenticating: "Mirkaneessaa jira...",
            no_account: "Eenyummeessa hin qabduu?",
            
            sign_up: "Galmaa'i",
            footer: "© 2026 Bulchiinsa Magaalaa Adaamaa - Inisheetiivii Magaalaa Smartii"
        },
        history: {
            qr_pass: 'QR Pass',
            actions: 'Gochaawwan',
            zoom: 'Guddisi',
            btn_ticket: 'Tikiteetti',
            btn_download: 'PDF buufadhu',
            btn_close: 'Cufi',
            qr_title: 'Waraqaa Seensaa',
            general_access: 'Daawwannaa Idilee',
            empty_feedback: 'Yaanni dhiyaate hin jiru.',
            swal_title: 'Haquu barbaadu?',
            swal_text: 'Iddoo qabachuu kana haquu keessan mirkaneessitanii?',
            swal_confirm: 'Eeyyee, haqui!'
        },
        notifications: {
            title: 'Giddu-gala Beeksisaa',
            subtitle: 'Odeeffannoo dursa qabaniifi jijjiirama sagantaa bulchaa',
            emergency_title: 'Beeksisa Ariifachiisaa',
            emergency_desc: 'Hubachiisa: Sagantaa gaalarii ilaalchisee odeeffannoo ariifachiisaa {count} qabdu. Maaloo beeksisa mallatteeffaman gaditti ilaalaa.',
            clear_all: 'Hunda Haqui',
            mark_read: 'Hunda akka dubbisameetti mallatteessi',
            filter_all: 'Beeksisa Hundaa',
            filter_unread: 'Kan hin dubbisamne',
            filter_important: 'Iddoo dursa qaban qofa',
            empty_title: 'Hundi xumurameera!',
            empty_desc: 'Ramaddii kanaaf beeksisi argame hin jiru.',
            suggested_slot: 'Yeroo Haaraa Yaadame',
            accept_rebook: 'Fudhadhu & Deebisii Galmeessi',
            confirm_delete: 'Beeksisa kana haquu barbaadu?',
            confirm_clear: 'Beeksisa hunda haquu barbaadu?'
        },
        feedback: {
            title: 'Yaada Ergi',
            header: 'Yaada Daawwattootaa',
            type_general: 'Waliigala',
            type_hall: 'Galma qofa',
            label_hall: 'Galma Filadhu',
            placeholder_hall: 'Bakka tokko filadhu...',
            label_subject: 'Dhimma',
            placeholder_subject: 'Waa’ee maaliiti?',
            label_rating: 'Sadarkaa Kenni',
            label_message: 'Yaada Keessan',
            placeholder_message: 'Waa’ee daawwannaa keessanii dabalata nuuf hime...',
            btn_add_photo: 'Suuraa Galchi',
            btn_cancel: 'Haqui',
            btn_submit: 'Yaada Ergi',
            sending: 'Ergamaa jira...',
            error_gibberish_title: 'Ergaa hin dubbisamne',
            error_gibberish_text: 'Maaloo jechoota ifa ta’an fi iddoo (space) fayyadamanii yaada keessan barreessaa.',
            success_title: 'Milkaa’eera!',
            success_text: 'Galatoomaa! Yaanni keessan bulchiinsaaf ergameera.',
        },
        feedbacks_for_guide: {
            title: "Yaada",
            portal_label: "Portaalii Qajeelfamaa • Gammachuu Daawwattootaa Hordofuu",
            search_placeholder: "Daawwataa ykn yaada barbaadi...",
            received: "Kan fudhatame",
            visitor: "Daawwataa",
            no_feedback: "Yaanni hin argamne kan",
            delete_confirm: "Yaada kana tarree keessan keessaa haquu barbaadu?",
            today: "Har'a"
        },
        guide_scanner: {
            title: "Mirkaneessa Seensaa",
            start_camera: "Kaameraa Jalqabi",
            ready: "Dubbisuuf qophiidha...",
            scanning: "Dubbisamaa jira...",
            access_granted: "Hayyamameera",
            access_denied: "Tiketiin sirrii miti"
        },
        // ... existing keys
        guide_login: {
            title: 'Qajeelfama',
            portal: 'Portal',
            subtitle: 'Seensa Buufata Ofischaalaa',
            hall_label: 'Galma Gaalarii Ramadame',
            hall_placeholder: 'Buufata keessan filadhaa',
            email_label: 'Imeeyilii Hojii',
            password_label: 'Iggitaa Nageenyaa',
            remember: 'Buufata kana yaadadhu',
            btn_access: 'Hayyama Mirkaneessi',
            btn_verifying: 'Mirkaneessaa jira...',
            back_link: 'Gara Karra Guddaatti Deebi’i'
        },
    profile: {
            subtitle: 'Odeeffannoo kee ilaali',
            email: 'Imeeyilii',
            phone: 'Bilbila',
            security_footer: 'Odeeffannoon kee eegamaadha'
        },

        
         guide_feedback: {
            title: "Yaada",
            feedbacks: "Yaada",
            subtitle: "Portal Qajeelfamaa",
            search: "Daawwataa ykn yaada barbaadi...",
            visitor: "Daawwataa",
            received: "Fudhatame",
            today: "Har'a",
            empty: "Hin argamne",
            confirm_delete: "Yaada kana haquu barbaadduu?"
        }
    }
};

// --- i18n Instance ---
const i18n = createI18n({
    legacy: false, 
    locale: localStorage.getItem('lang') || 'om',
    fallbackLocale: 'en',
    messages,
});

createInertiaApp({
    title: (title) => (title ? `${title} - ${appName}` : appName),
    resolve: (name) => resolvePageComponent(`./Pages/${name}.vue`, import.meta.glob('./Pages/**/*.vue')),
    setup({ el, App, props, plugin }) {
        const app = createApp({ render: () => h(App, props) });

        app.use(plugin)
           .use(ZiggyVue, window.Ziggy)
           .use(i18n);

        // Make translation function global
        app.config.globalProperties.$t = i18n.global.t;

        // Watch for language changes to update localStorage and document attributes
        watch(
            () => i18n.global.locale.value,
            (val) => {
                localStorage.setItem('lang', val);
                document.documentElement.lang = val;
            },
            { immediate: true }
        );

        return app.mount(el);
    },
    progress: {
        color: '#4B5563',
    },
});